import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de almuerzos cubanos e internacionales
 */
export const ALMUERZOS: Recipe[] = [
  {
    id: generateId(),
    title: "Arroz Congrí Cubano",
    ingredients: [
      { name: "arroz", quantity: "2", unit: "tazas" },
      { name: "frijoles negros", quantity: "1", unit: "taza" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento", quantity: "1", unit: "mediano" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Remojar los frijoles negros en agua durante 4 horas o durante la noche",
      "Cocinar los frijoles en agua con sal hasta que estén tiernos",
      "En una olla grande, calentar el aceite y sofreír la cebolla, el pimiento y el ajo picados",
      "Añadir el comino y mezclar bien",
      "Agregar el arroz y mezclar para que se impregne del sofrito",
      "Añadir los frijoles con parte de su caldo de cocción",
      "Ajustar la sal y cocinar a fuego bajo hasta que el arroz esté listo",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Atún y Vegetales (Sin Electricidad)",
    ingredients: [
      { name: "atún en lata", quantity: "1", unit: "lata" },
      { name: "tomate", quantity: "1", unit: "grande" },
      { name: "pepino", quantity: "1", unit: "mediano" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Escurrir el atún y desmenuzarlo en un recipiente",
      "Lavar y cortar el tomate y el pepino en cubos pequeños",
      "Picar finamente la cebolla",
      "Mezclar todos los vegetales con el atún",
      "Aliñar con jugo de limón, aceite de oliva y sal al gusto",
      "Mezclar bien y servir inmediatamente o refrigerar",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ropa Vieja Cubana",
    ingredients: [
      { name: "carne de res", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "grande" },
      { name: "pimiento", quantity: "1", unit: "grande" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "salsa de tomate", quantity: "1/2", unit: "taza" },
      { name: "aceite", quantity: "3", unit: "cucharadas" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "orégano", quantity: "1", unit: "cucharadita" },
      { name: "laurel", quantity: "2", unit: "hojas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "pimienta", quantity: "1/2", unit: "cucharadita" },
    ],
    instructions: [
      "Cocinar la carne en agua con sal, cebolla, ajo y laurel hasta que esté tierna",
      "Retirar la carne y desmenuzarla usando dos tenedores",
      "En una sartén grande, calentar el aceite y sofreír la cebolla y el pimiento cortados en juliana",
      "Agregar el ajo picado, el comino y el orégano",
      "Añadir la carne desmenuzada y la salsa de tomate",
      "Cocinar a fuego medio-bajo por 20 minutos, revolviendo ocasionalmente",
      "Rectificar la sazón con sal y pimienta",
      "Servir caliente con arroz blanco",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz con Pollo Cubano",
    ingredients: [
      { name: "arroz", quantity: "2", unit: "tazas" },
      { name: "pollo en piezas", quantity: "1", unit: "kg" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento", quantity: "1", unit: "mediano" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "cerveza", quantity: "1", unit: "taza" },
      { name: "salsa de tomate", quantity: "1/4", unit: "taza" },
      { name: "colorante alimentario", quantity: "1/2", unit: "cucharadita" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "guisantes", quantity: "1/2", unit: "taza" },
      { name: "pimientos morrones", quantity: "1/4", unit: "taza" },
    ],
    instructions: [
      "Sazonar el pollo con sal, comino y ajo machacado",
      "En una cazuela, calentar el aceite y dorar el pollo por todos lados",
      "Retirar el pollo y en el mismo aceite, sofreír la cebolla y el pimiento picados",
      "Añadir el ajo y cocinar por 1 minuto más",
      "Agregar la salsa de tomate y el colorante",
      "Devolver el pollo a la cazuela y añadir el arroz",
      "Verter la cerveza y agua suficiente para cubrir 1 cm por encima del arroz",
      "Cocinar a fuego medio-bajo hasta que el arroz esté tierno",
      "Añadir los guisantes y los pimientos morrones al final",
      "Dejar reposar tapado por 5 minutos antes de servir",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Yuca con Mojo Criollo",
    ingredients: [
      { name: "yuca", quantity: "1", unit: "kg" },
      { name: "ajo", quantity: "6", unit: "dientes" },
      { name: "cebolla", quantity: "1/2", unit: "unidad" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "naranja agria", quantity: "1", unit: "unidad" },
      { name: "aceite de oliva", quantity: "1/4", unit: "taza" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "orégano", quantity: "1/2", unit: "cucharadita" },
    ],
    instructions: [
      "Pelar la yuca y cortarla en trozos de 5-6 cm",
      "Hervir la yuca en agua con sal hasta que esté tierna (30-40 minutos)",
      "Mientras tanto, preparar el mojo: picar el ajo y la cebolla finamente",
      "Calentar el aceite en una sartén pequeña",
      "Añadir el ajo y la cebolla, cocinar a fuego lento sin que se doren",
      "Exprimir el limón y la naranja agria, añadir el jugo a la sartén",
      "Añadir el orégano y la sal, cocinar por 2 minutos más",
      "Escurrir la yuca y colocarla en una fuente",
      "Verter el mojo caliente sobre la yuca",
      "Servir inmediatamente",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Potaje de Frijoles Negros Cubano",
    ingredients: [
      { name: "frijoles negros", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "grande" },
      { name: "pimiento", quantity: "1", unit: "grande" },
      { name: "ajo", quantity: "4", unit: "dientes" },
      { name: "aceite de oliva", quantity: "3", unit: "cucharadas" },
      { name: "vinagre", quantity: "1", unit: "cucharada" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "azúcar", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "pimienta", quantity: "1/4", unit: "cucharadita" },
    ],
    instructions: [
      "Lavar los frijoles y remojarlos en agua durante la noche",
      "Escurrir y colocar en una olla grande con agua fresca",
      "Añadir la hoja de laurel y cocinar a fuego medio hasta que estén tiernos (1-2 horas)",
      "En una sartén, calentar el aceite y sofreír la cebolla y el pimiento picados",
      "Añadir el ajo picado y el comino, cocinar por 1 minuto más",
      "Incorporar el sofrito a la olla de frijoles",
      "Añadir el vinagre, azúcar, sal y pimienta",
      "Cocinar a fuego lento por 30 minutos más, removiendo ocasionalmente",
      "Si deseas, puedes machacar algunos frijoles para espesar la sopa",
      "Servir caliente, tradicionalmente con arroz blanco",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
];
