import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de almuerzos cubanos e internacionales
 */
export const ALMUERZOS: Recipe[] = [
  // Recetas existentes (manteniendo las originales)
  {
    id: generateId(),
    title: "Arroz Congrí Cubano",
    ingredients: [
      { name: "arroz", quantity: "2", unit: "tazas" },
      { name: "frijoles negros", quantity: "1", unit: "taza" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento", quantity: "1", unit: "mediano" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Remojar los frijoles negros en agua durante 4 horas o durante la noche",
      "Cocinar los frijoles en agua con sal hasta que estén tiernos",
      "En una olla grande, calentar el aceite y sofreír la cebolla, el pimiento y el ajo picados",
      "Añadir el comino y mezclar bien",
      "Agregar el arroz y mezclar para que se impregne del sofrito",
      "Añadir los frijoles con parte de su caldo de cocción",
      "Ajustar la sal y cocinar a fuego bajo hasta que el arroz esté listo",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Atún y Vegetales (Sin Electricidad)",
    ingredients: [
      { name: "atún en lata", quantity: "1", unit: "lata" },
      { name: "tomate", quantity: "1", unit: "grande" },
      { name: "pepino", quantity: "1", unit: "mediano" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Escurrir el atún y desmenuzarlo en un recipiente",
      "Lavar y cortar el tomate y el pepino en cubos pequeños",
      "Picar finamente la cebolla",
      "Mezclar todos los vegetales con el atún",
      "Aliñar con jugo de limón, aceite de oliva y sal al gusto",
      "Mezclar bien y servir inmediatamente o refrigerar",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ropa Vieja Cubana",
    ingredients: [
      { name: "carne de res", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "grande" },
      { name: "pimiento", quantity: "1", unit: "grande" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "salsa de tomate", quantity: "1/2", unit: "taza" },
      { name: "aceite", quantity: "3", unit: "cucharadas" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "orégano", quantity: "1", unit: "cucharadita" },
      { name: "laurel", quantity: "2", unit: "hojas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "pimienta", quantity: "1/2", unit: "cucharadita" },
    ],
    instructions: [
      "Cocinar la carne en agua con sal, cebolla, ajo y laurel hasta que esté tierna",
      "Retirar la carne y desmenuzarla usando dos tenedores",
      "En una sartén grande, calentar el aceite y sofreír la cebolla y el pimiento cortados en juliana",
      "Agregar el ajo picado, el comino y el orégano",
      "Añadir la carne desmenuzada y la salsa de tomate",
      "Cocinar a fuego medio-bajo por 20 minutos, revolviendo ocasionalmente",
      "Rectificar la sazón con sal y pimienta",
      "Servir caliente con arroz blanco",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz con Pollo Cubano",
    ingredients: [
      { name: "arroz", quantity: "2", unit: "tazas" },
      { name: "pollo en piezas", quantity: "1", unit: "kg" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento", quantity: "1", unit: "mediano" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "cerveza", quantity: "1", unit: "taza" },
      { name: "salsa de tomate", quantity: "1/4", unit: "taza" },
      { name: "colorante alimentario", quantity: "1/2", unit: "cucharadita" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "guisantes", quantity: "1/2", unit: "taza" },
      { name: "pimientos morrones", quantity: "1/4", unit: "taza" },
    ],
    instructions: [
      "Sazonar el pollo con sal, comino y ajo machacado",
      "En una cazuela, calentar el aceite y dorar el pollo por todos lados",
      "Retirar el pollo y en el mismo aceite, sofreír la cebolla y el pimiento picados",
      "Añadir el ajo y cocinar por 1 minuto más",
      "Agregar la salsa de tomate y el colorante",
      "Devolver el pollo a la cazuela y añadir el arroz",
      "Verter la cerveza y agua suficiente para cubrir 1 cm por encima del arroz",
      "Cocinar a fuego medio-bajo hasta que el arroz esté tierno",
      "Añadir los guisantes y los pimientos morrones al final",
      "Dejar reposar tapado por 5 minutos antes de servir",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Yuca con Mojo Criollo",
    ingredients: [
      { name: "yuca", quantity: "1", unit: "kg" },
      { name: "ajo", quantity: "6", unit: "dientes" },
      { name: "cebolla", quantity: "1/2", unit: "unidad" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "naranja agria", quantity: "1", unit: "unidad" },
      { name: "aceite de oliva", quantity: "1/4", unit: "taza" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "orégano", quantity: "1/2", unit: "cucharadita" },
    ],
    instructions: [
      "Pelar la yuca y cortarla en trozos de 5-6 cm",
      "Hervir la yuca en agua con sal hasta que esté tierna (30-40 minutos)",
      "Mientras tanto, preparar el mojo: picar el ajo y la cebolla finamente",
      "Calentar el aceite en una sartén pequeña",
      "Añadir el ajo y la cebolla, cocinar a fuego lento sin que se doren",
      "Exprimir el limón y la naranja agria, añadir el jugo a la sartén",
      "Añadir el orégano y la sal, cocinar por 2 minutos más",
      "Escurrir la yuca y colocarla en una fuente",
      "Verter el mojo caliente sobre la yuca",
      "Servir inmediatamente",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Potaje de Frijoles Negros Cubano",
    ingredients: [
      { name: "frijoles negros", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "grande" },
      { name: "pimiento", quantity: "1", unit: "grande" },
      { name: "ajo", quantity: "4", unit: "dientes" },
      { name: "aceite de oliva", quantity: "3", unit: "cucharadas" },
      { name: "vinagre", quantity: "1", unit: "cucharada" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "azúcar", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "pimienta", quantity: "1/4", unit: "cucharadita" },
    ],
    instructions: [
      "Lavar los frijoles y remojarlos en agua durante la noche",
      "Escurrir y colocar en una olla grande con agua fresca",
      "Añadir la hoja de laurel y cocinar a fuego medio hasta que estén tiernos (1-2 horas)",
      "En una sartén, calentar el aceite y sofreír la cebolla y el pimiento picados",
      "Añadir el ajo picado y el comino, cocinar por 1 minuto más",
      "Incorporar el sofrito a la olla de frijoles",
      "Añadir el vinagre, azúcar, sal y pimienta",
      "Cocinar a fuego lento por 30 minutos más, removiendo ocasionalmente",
      "Si deseas, puedes machacar algunos frijoles para espesar la sopa",
      "Servir caliente, tradicionalmente con arroz blanco",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Lentejas Estofadas (Internacional)",
    ingredients: [
      { name: "lentejas pardinas", quantity: "250", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "zanahoria", quantity: "1", unit: "grande" },
      { name: "pimiento rojo", quantity: "1/2", unit: "unidad" },
      { name: "ajo", quantity: "2", unit: "dientes" },
      { name: "chorizo", quantity: "100", unit: "gramos" },
      { name: "pimentón dulce", quantity: "1", unit: "cucharadita" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "caldo de verduras o agua", quantity: "1", unit: "litro" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Lavar las lentejas y escurrir.",
      "Picar finamente la cebolla, zanahoria y pimiento.",
      "Pelar y picar el ajo.",
      "Cortar el chorizo en rodajas.",
      "En una olla grande, calentar el aceite y sofreír la cebolla, zanahoria y pimiento hasta que estén blandos.",
      "Añadir el ajo y el chorizo, cocinar por unos minutos.",
      "Incorporar el pimentón y remover rápidamente.",
      "Agregar las lentejas, la hoja de laurel y el caldo o agua.",
      "Llevar a ebullición, luego reducir el fuego y cocinar a fuego lento por 30-40 minutos, o hasta que las lentejas estén tiernas.",
      "Remover ocasionalmente y añadir más líquido si es necesario.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada César con Pollo (Internacional)",
    ingredients: [
      { name: "pechuga de pollo", quantity: "1", unit: "unidad" },
      { name: "lechuga romana", quantity: "1", unit: "unidad" },
      { name: "picatostes", quantity: "1", unit: "taza" },
      { name: "queso parmesano rallado", quantity: "1/4", unit: "taza" },
      { name: "aderezo César", quantity: "1/2", unit: "taza" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Sazonar la pechuga de pollo con sal y pimienta.",
      "Calentar el aceite de oliva en una sartén y cocinar el pollo por ambos lados hasta que esté bien cocido.",
      "Dejar reposar el pollo por unos minutos y luego cortarlo en rebanadas o cubos.",
      "Lavar y picar la lechuga romana en trozos grandes.",
      "En un bol grande, combinar la lechuga, los picatostes, el queso parmesano y el pollo cocido.",
      "Verter el aderezo César sobre la ensalada.",
      "Mezclar suavemente para cubrir todos los ingredientes.",
      "Servir inmediatamente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sándwich de Medianoche Cubano",
    ingredients: [
      { name: "pan de medianoche", quantity: "1", unit: "unidad" },
      { name: "jamón de cerdo", quantity: "50", unit: "gramos" },
      { name: "queso suizo", quantity: "2", unit: "lonchas" },
      { name: "pepinillos encurtidos", quantity: "3", unit: "rodajas" },
      { name: "mostaza", quantity: "1", unit: "cucharada" },
      { name: "mantequilla", quantity: "1", unit: "cucharada" },
    ],
    instructions: [
      "Cortar el pan de medianoche por la mitad horizontalmente.",
      "Untar mostaza en la parte interior de ambas mitades del pan.",
      "Colocar el jamón, el queso suizo y las rodajas de pepinillo sobre una mitad del pan.",
      "Cubrir con la otra mitad del pan para formar el sándwich.",
      "Untar mantequilla en la parte exterior del sándwich.",
      "Calentar una plancha o sartén a fuego medio.",
      "Cocinar el sándwich en la plancha, presionando ligeramente, hasta que esté dorado y el queso derretido por ambos lados.",
      "Cortar por la mitad y servir caliente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ajiaco Cubano",
    ingredients: [
      { name: "carne de res (falda o pecho)", quantity: "500", unit: "gramos" },
      {
        name: "pollo (muslos o contramuslos)",
        quantity: "500",
        unit: "gramos",
      },
      { name: "maíz tierno", quantity: "2", unit: "mazorcas" },
      { name: "malanga", quantity: "250", unit: "gramos" },
      { name: "boniato (batata)", quantity: "250", unit: "gramos" },
      { name: "yuca", quantity: "250", unit: "gramos" },
      { name: "calabaza (ahuyama)", quantity: "250", unit: "gramos" },
      { name: "plátano verde", quantity: "1", unit: "unidad" },
      { name: "cebolla", quantity: "1", unit: "grande" },
      { name: "pimiento verde", quantity: "1", unit: "grande" },
      { name: "ajo", quantity: "4", unit: "dientes" },
      { name: "tomate", quantity: "2", unit: "unidades" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "orégano", quantity: "1", unit: "cucharadita" },
      { name: "laurel", quantity: "2", unit: "hojas" },
      { name: "aceite de oliva", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla grande, cocinar la carne de res y el pollo en agua con sal y laurel hasta que estén tiernos.",
      "Retirar las carnes, desmenuzar la de res y deshuesar el pollo. Reservar el caldo.",
      "Pelar y cortar todas las viandas (maíz, malanga, boniato, yuca, calabaza, plátano verde) en trozos grandes.",
      "En una sartén, calentar el aceite y sofreír la cebolla, pimiento y ajo picados.",
      "Añadir el tomate picado, comino y orégano. Cocinar por unos minutos.",
      "En la olla con el caldo reservado, añadir las viandas y el sofrito.",
      "Cocinar a fuego medio hasta que las viandas estén blandas y el caldo espese ligeramente.",
      "Añadir las carnes desmenuzadas y cocinar por 10 minutos más.",
      "Rectificar la sazón con sal y pimienta.",
      "Servir caliente en tazones grandes.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Avanzada",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Paella Valenciana (Internacional, Avanzada)",
    ingredients: [
      { name: "arroz bomba", quantity: "400", unit: "gramos" },
      { name: "pollo troceado", quantity: "300", unit: "gramos" },
      { name: "conejo troceado", quantity: "300", unit: "gramos" },
      { name: "judías verdes planas", quantity: "200", unit: "gramos" },
      { name: "garrofón", quantity: "100", unit: "gramos" },
      { name: "tomate triturado", quantity: "150", unit: "gramos" },
      { name: "pimentón dulce", quantity: "1", unit: "cucharadita" },
      { name: "azafrán en hebras", quantity: "unas hebras", unit: "unidad" },
      { name: "caldo de pollo o verduras", quantity: "1.5", unit: "litros" },
      { name: "aceite de oliva virgen extra", quantity: "1/4", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "romero fresco (opcional)", quantity: "una ramita", unit: "unidad" },
    ],
    instructions: [
      "En una paellera grande, calentar el aceite de oliva a fuego medio-alto.",
      "Dorar el pollo y el conejo troceados por todos lados. Retirar y reservar.",
      "En el mismo aceite, sofreír las judías verdes y el garrofón por unos minutos.",
      "Añadir el tomate triturado y cocinar hasta que reduzca.",
      "Incorporar el pimentón dulce y remover rápidamente.",
      "Volver a añadir las carnes a la paellera.",
      "Añadir el arroz y remover para que se impregne de los sabores.",
      "Verter el caldo caliente con el azafrán disuelto. Asegurarse de que el caldo cubra el arroz uniformemente.",
      "Añadir sal al gusto y la ramita de romero (si se usa).",
      "Cocinar a fuego alto por unos 10 minutos, luego reducir el fuego a medio-bajo y cocinar por otros 10-15 minutos, o hasta que el arroz absorba el líquido y se forme el 'socarrat' (capa tostada en el fondo). No remover el arroz mientras se cocina.",
      "Retirar del fuego, tapar con un paño limpio o papel de aluminio y dejar reposar por 5-10 minutos antes de servir.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Avanzada",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Gazpacho Andaluz (Internacional, Sin Electricidad, Bajo en Calorías)",
    ingredients: [
      { name: "tomates maduros", quantity: "1", unit: "kg" },
      { name: "pepino", quantity: "1", unit: "unidad" },
      { name: "pimiento verde", quantity: "1/2", unit: "unidad" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "ajo", quantity: "1", unit: "diente" },
      {
        name: "pan del día anterior",
        quantity: "50",
        unit: "gramos (remojado)",
      },
      { name: "aceite de oliva virgen extra", quantity: "50", unit: "ml" },
      { name: "vinagre de jerez", quantity: "2", unit: "cucharadas" },
      { name: "agua fría", quantity: "100", unit: "ml" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Lavar y trocear los tomates, pepino, pimiento y cebolla.",
      "Pelar el ajo.",
      "Remojar el pan en un poco de agua.",
      "En un recipiente grande, combinar todos los vegetales troceados, el ajo y el pan remojado (escurrido).",
      "Con un mortero o machacador, triturar los ingredientes hasta obtener una pasta lo más fina posible. (Nota: La textura no será tan suave como con una batidora).",
      "Añadir el aceite de oliva, el vinagre y la sal.",
      "Incorporar el agua fría y mezclar bien.",
      "Probar y ajustar la sazón si es necesario.",
      "Servir frío, opcionalmente con picatostes o vegetales picados por encima.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Fideuá de Mariscos (Internacional, Intermedia)",
    ingredients: [
      { name: "fideos para fideuá", quantity: "300", unit: "gramos" },
      { name: "gambas", quantity: "200", unit: "gramos" },
      { name: "calamares limpios", quantity: "200", unit: "gramos" },
      { name: "mejillones", quantity: "500", unit: "gramos" },
      { name: "tomate triturado", quantity: "100", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "pequeña" },
      { name: "ajo", quantity: "2", unit: "dientes" },
      { name: "pimentón dulce", quantity: "1", unit: "cucharadita" },
      { name: "caldo de pescado o marisco", quantity: "1", unit: "litro" },
      { name: "aceite de oliva virgen extra", quantity: "1/4", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Limpiar las gambas y calamares. Cortar los calamares en aros.",
      "Limpiar bien los mejillones.",
      "Picar finamente la cebolla y el ajo.",
      "En una paellera o sartén grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir los calamares y cocinar por unos minutos.",
      "Incorporar el tomate triturado y cocinar hasta que reduzca.",
      "Añadir el pimentón dulce y remover rápidamente.",
      "Agregar los fideos y remover para que se doren ligeramente.",
      "Verter el caldo de pescado caliente. Asegurarse de que el caldo cubra los fideos.",
      "Añadir sal al gusto.",
      "Cocinar a fuego medio-alto por unos 10-12 minutos, o hasta que los fideos estén cocidos y el líquido se haya absorbido. Añadir las gambas y mejillones en los últimos 5 minutos de cocción.",
      "Retirar del fuego y dejar reposar por unos minutos antes de servir.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  // --- 15 Recetas adicionales para Almuerzo ---
  {
    id: generateId(),
    title: "Pescado con Arroz y Ensalada (Cubana)",
    ingredients: [
      { name: "filetes de pescado blanco", quantity: "2", unit: "unidades" },
      { name: "arroz blanco cocido", quantity: "1", unit: "taza" },
      { name: "lechuga", quantity: "1", unit: "taza picada" },
      { name: "tomate", quantity: "1/2", unit: "unidad en rodajas" },
      { name: "pepino", quantity: "1/4", unit: "unidad en rodajas" },
      { name: "limón", quantity: "1/2", unit: "unidad" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      {
        name: "harina de trigo",
        quantity: "2",
        unit: "cucharadas (para enharinar)",
      },
      { name: "aceite para freír", quantity: "suficiente", unit: "unidad" },
    ],
    instructions: [
      "Sazonar los filetes de pescado con sal y pimienta. Enharinar ligeramente.",
      "Calentar aceite en una sartén a fuego medio-alto y freír el pescado hasta que esté dorado y cocido por ambos lados.",
      "Lavar y cortar la lechuga, tomate y pepino para la ensalada.",
      "Aliñar la ensalada con jugo de limón, aceite de oliva, sal y pimienta.",
      "Servir el pescado frito caliente acompañado de arroz blanco cocido y la ensalada fresca.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Fricasé de Pollo Cubano",
    ingredients: [
      { name: "pollo en piezas", quantity: "1", unit: "kg" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento verde", quantity: "1", unit: "mediano" },
      { name: "ajo", quantity: "4", unit: "dientes" },
      { name: "salsa de tomate", quantity: "1/2", unit: "taza" },
      { name: "vino seco", quantity: "1/4", unit: "taza" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "orégano", quantity: "1", unit: "cucharadita" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "papas", quantity: "2", unit: "medianas en cubos" },
      { name: "zanahorias", quantity: "1", unit: "grande en rodajas" },
      { name: "guisantes", quantity: "1/4", unit: "taza" },
      { name: "aceite", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Sazonar el pollo con sal, pimienta, comino y orégano.",
      "En una cazuela grande, calentar el aceite y dorar el pollo por todos lados. Retirar.",
      "En el mismo aceite, sofreír la cebolla, pimiento y ajo picados.",
      "Añadir la salsa de tomate, vino seco y la hoja de laurel. Cocinar por unos minutos.",
      "Regresar el pollo a la cazuela. Añadir agua o caldo suficiente para casi cubrir el pollo.",
      "Llevar a ebullición, luego reducir el fuego y cocinar a fuego lento por 30 minutos.",
      "Añadir las papas y zanahorias. Cocinar por 20-30 minutos más, o hasta que las verduras estén tiernas y la salsa espese.",
      "Incorporar los guisantes en los últimos 5 minutos.",
      "Rectificar la sazón.",
      "Servir caliente, tradicionalmente con arroz blanco.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tamal en Cazuela Cubano",
    ingredients: [
      { name: "maíz tierno (granos)", quantity: "4", unit: "tazas" },
      {
        name: "carne de cerdo (paleta o pernil)",
        quantity: "500",
        unit: "gramos cocida y desmenuzada",
      },
      { name: "cebolla", quantity: "1", unit: "mediana picada" },
      { name: "pimiento verde", quantity: "1", unit: "mediano picado" },
      { name: "ajo", quantity: "3", unit: "dientes picados" },
      { name: "salsa de tomate", quantity: "1/4", unit: "taza" },
      { name: "manteca de cerdo o aceite", quantity: "1/4", unit: "taza" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "orégano", quantity: "1", unit: "cucharadita" },
      {
        name: "achiote o colorante",
        quantity: "1/2",
        unit: "cucharadita (opcional)",
      },
      { name: "caldo de carne o agua", quantity: "2", unit: "tazas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Licuar los granos de maíz tierno con un poco de caldo hasta obtener una pasta suave.",
      "En una cazuela grande, calentar la manteca o aceite a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo picados.",
      "Añadir la carne de cerdo desmenuzada, salsa de tomate, comino, orégano y achiote (si se usa). Cocinar por unos minutos.",
      "Incorporar la pasta de maíz licuado y el caldo restante.",
      "Cocinar a fuego medio-bajo, revolviendo constantemente con una cuchara de madera, hasta que espese y se cocine el maíz (aproximadamente 20-30 minutos).",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente en tazones.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Bistec de Res Empanizado (Milanesa) con Moros y Cristianos (Cubana)",
    ingredients: [
      {
        name: "bistec de res (nalga o palomilla)",
        quantity: "2",
        unit: "filetes finos",
      },
      { name: "pan rallado", quantity: "1", unit: "taza" },
      { name: "huevo", quantity: "1", unit: "unidad batida" },
      { name: "harina de trigo", quantity: "1/4", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "aceite para freír", quantity: "suficiente", unit: "unidad" },
      { name: "arroz blanco cocido", quantity: "1", unit: "taza" },
      {
        name: "frijoles negros cocidos (enteros)",
        quantity: "1",
        unit: "taza",
      },
      { name: "cebolla", quantity: "1/4", unit: "unidad picada" },
      { name: "pimiento verde", quantity: "1/4", unit: "unidad picado" },
      { name: "ajo", quantity: "1", unit: "diente picado" },
      { name: "comino", quantity: "1/4", unit: "cucharadita" },
      { name: "aceite", quantity: "1", unit: "cucharada (para los moros)" },
    ],
    instructions: [
      "Sazonar los filetes de bistec con sal y pimienta.",
      "Pasar cada bistec por harina, luego por huevo batido y finalmente por pan rallado, cubriendo bien.",
      "Calentar suficiente aceite en una sartén a fuego medio-alto y freír los bistecs empanizados hasta que estén dorados y crujientes por ambos lados.",
      "Retirar y colocar sobre papel absorbente.",
      "Para los Moros y Cristianos: En una sartén, calentar el aceite a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo picados hasta que estén transparentes.",
      "Añadir los frijoles negros cocidos (con un poco de su caldo) y el comino.",
      "Incorporar el arroz blanco cocido y mezclar bien.",
      "Cocinar por unos minutos hasta que esté todo caliente y bien combinado.",
      "Servir el bistec empanizado caliente acompañado de Moros y Cristianos.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Pollo y Vegetales (Internacional, Bajo en Calorías)",
    ingredients: [
      { name: "pechuga de pollo", quantity: "1", unit: "unidad" },
      { name: "zanahorias", quantity: "2", unit: "unidades en rodajas" },
      { name: "apio", quantity: "2", unit: "tallos en rodajas" },
      { name: "papas", quantity: "1", unit: "mediana en cubos" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "caldo de pollo", quantity: "1.5", unit: "litros" },
      { name: "perejil fresco", quantity: "2", unit: "cucharadas picado" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir la pechuga de pollo entera, zanahorias, apio y papas.",
      "Verter el caldo de pollo. Llevar a ebullición.",
      "Reducir el fuego, tapar y cocinar a fuego lento por 20-25 minutos, o hasta que el pollo esté cocido y los vegetales tiernos.",
      "Retirar la pechuga de pollo, desmenuzarla y regresarla a la sopa.",
      "Añadir el perejil picado.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada Griega (Internacional, Vegetariano)",
    ingredients: [
      { name: "tomates", quantity: "2", unit: "unidades en cubos grandes" },
      { name: "pepino", quantity: "1", unit: "unidad en cubos grandes" },
      {
        name: "pimiento verde",
        quantity: "1",
        unit: "unidad en cubos grandes",
      },
      {
        name: "cebolla roja",
        quantity: "1/2",
        unit: "unidad en rodajas finas",
      },
      { name: "aceitunas Kalamata", quantity: "1/2", unit: "taza" },
      {
        name: "queso feta",
        quantity: "100",
        unit: "gramos en cubos o desmenuzado",
      },
      { name: "orégano seco", quantity: "1", unit: "cucharadita" },
      { name: "aceite de oliva virgen extra", quantity: "1/4", unit: "taza" },
      { name: "vinagre de vino tinto", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol grande, combinar los tomates, pepino, pimiento verde y cebolla roja.",
      "Añadir las aceitunas Kalamata y el queso feta.",
      "En un bol pequeño, batir el aceite de oliva, vinagre, orégano, sal y pimienta para hacer el aderezo.",
      "Verter el aderezo sobre la ensalada.",
      "Mezclar suavemente para combinar.",
      "Servir inmediatamente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pasta con Pesto y Tomates Cherry (Internacional, Vegetariano)",
    ingredients: [
      { name: "pasta (espagueti, fusilli)", quantity: "250", unit: "gramos" },
      { name: "pesto", quantity: "1/2", unit: "taza" },
      {
        name: "tomates cherry",
        quantity: "200",
        unit: "gramos partidos por la mitad",
      },
      { name: "queso parmesano rallado", quantity: "1/4", unit: "taza" },
      {
        name: "piñones tostados (opcional)",
        quantity: "2",
        unit: "cucharadas",
      },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Cocer la pasta en agua hirviendo con sal según las instrucciones del paquete. Reservar un poco del agua de cocción antes de escurrir.",
      "Mientras la pasta se cuece, calentar el aceite de oliva en una sartén grande a fuego medio.",
      "Añadir los tomates cherry partidos y cocinar por unos minutos hasta que se ablanden ligeramente.",
      "Escurrir la pasta y añadirla a la sartén con los tomates.",
      "Agregar el pesto y mezclar bien. Si la salsa está muy espesa, añadir un poco del agua de cocción reservada.",
      "Incorporar la mitad del queso parmesano y los piñones tostados (si se usan).",
      "Servir caliente, espolvoreado con el queso parmesano restante.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Lentejas (Sin Electricidad, Bajo en Grasas)",
    ingredients: [
      { name: "lentejas secas", quantity: "1", unit: "taza" },
      { name: "cebolla", quantity: "1", unit: "mediana picada" },
      { name: "zanahorias", quantity: "2", unit: "unidades en cubos" },
      { name: "apio", quantity: "2", unit: "tallos en cubos" },
      { name: "ajo", quantity: "3", unit: "dientes picados" },
      { name: "tomate triturado", quantity: "400", unit: "gramos" },
      { name: "caldo de verduras o agua", quantity: "1.5", unit: "litros" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "pimentón dulce", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Lavar las lentejas.",
      "En una olla grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla, zanahorias y apio hasta que estén blandos.",
      "Añadir el ajo picado, comino y pimentón. Cocinar por 1 minuto.",
      "Incorporar el tomate triturado, lentejas, caldo o agua y la hoja de laurel.",
      "Llevar a ebullición, luego reducir el fuego y cocinar a fuego lento por 30-40 minutos, o hasta que las lentejas estén tiernas.",
      "Retirar la hoja de laurel. Sazonar con sal y pimienta al gusto.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz a la Mexicana (Internacional, Estándar)",
    ingredients: [
      { name: "arroz blanco", quantity: "1", unit: "taza" },
      { name: "tomate", quantity: "2", unit: "unidades" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "ajo", quantity: "1", unit: "diente" },
      { name: "chícharos (guisantes)", quantity: "1/2", unit: "taza" },
      { name: "zanahoria", quantity: "1", unit: "unidad en cubos pequeños" },
      { name: "caldo de pollo o agua", quantity: "2", unit: "tazas" },
      { name: "aceite vegetal", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Licuar los tomates, cebolla y ajo con un poco de caldo o agua.",
      "En una olla, calentar el aceite vegetal a fuego medio.",
      "Añadir el arroz crudo y freír, revolviendo constantemente, hasta que esté ligeramente dorado.",
      "Verter la mezcla de tomate licuado sobre el arroz. Cocinar por unos minutos hasta que el líquido reduzca ligeramente.",
      "Añadir el caldo restante, los chícharos y la zanahoria.",
      "Sazonar con sal al gusto. Llevar a ebullición.",
      "Reducir el fuego al mínimo, tapar y cocinar por 15-20 minutos, o hasta que el arroz haya absorbido todo el líquido y esté tierno.",
      "Dejar reposar tapado por 5 minutos antes de servir.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Ensalada de Garbanzos (Sin Electricidad, Vegetariano, Alto en Proteínas)",
    ingredients: [
      { name: "garbanzos cocidos", quantity: "400", unit: "gramos" },
      { name: "pepino", quantity: "1/2", unit: "unidad en cubos" },
      { name: "tomate", quantity: "1", unit: "unidad en cubos" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      { name: "pimiento amarillo", quantity: "1/2", unit: "unidad en cubos" },
      { name: "perejil fresco", quantity: "2", unit: "cucharadas picado" },
      {
        name: "aceite de oliva virgen extra",
        quantity: "3",
        unit: "cucharadas",
      },
      { name: "jugo de limón", quantity: "2", unit: "cucharadas" },
      { name: "comino molido", quantity: "1/2", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol grande, combinar los garbanzos cocidos, pepino, tomate, cebolla roja, pimiento amarillo y perejil.",
      "En un bol pequeño, batir el aceite de oliva, jugo de limón, comino, sal y pimienta para hacer el aderezo.",
      "Verter el aderezo sobre la ensalada de garbanzos.",
      "Mezclar suavemente para combinar.",
      "Servir inmediatamente o refrigerar por un rato para que los sabores se mezclen.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Calabaza (Internacional, Bajo en Calorías)",
    ingredients: [
      { name: "calabaza (ahuyama)", quantity: "500", unit: "gramos en cubos" },
      { name: "cebolla", quantity: "1", unit: "mediana picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "caldo de verduras", quantity: "750", unit: "ml" },
      {
        name: "jengibre fresco",
        quantity: "1/2",
        unit: "cucharadita rallado (opcional)",
      },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      {
        name: "crema agria o yogur natural (para servir, opcional)",
        quantity: "al gusto",
        unit: "unidad",
      },
    ],
    instructions: [
      "En una olla grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla hasta que esté transparente.",
      "Añadir el ajo y el jengibre (si se usa), cocinar por 1 minuto.",
      "Incorporar los cubos de calabaza y el caldo de verduras.",
      "Llevar a ebullición, luego reducir el fuego, tapar y cocinar a fuego lento por 15-20 minutos, o hasta que la calabaza esté muy tierna.",
      "Retirar del fuego y triturar la sopa con una batidora de mano o en una licuadora hasta que esté suave. (Si no hay electricidad, machacar muy bien con un tenedor grande o pasapurés).",
      "Regresar la sopa a la olla (si se usó licuadora) y calentar suavemente.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, opcionalmente con una cucharada de crema agria o yogur natural.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Empanadas de Carne (Cubana)",
    ingredients: [
      {
        name: "discos de empanada (comprados o caseros)",
        quantity: "12",
        unit: "unidades",
      },
      { name: "carne molida", quantity: "250", unit: "gramos" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "pimiento", quantity: "1/4", unit: "unidad picado" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "salsa de tomate", quantity: "2", unit: "cucharadas" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "orégano", quantity: "1/4", unit: "cucharadita" },
      { name: "aceitunas verdes picadas", quantity: "2", unit: "cucharadas" },
      { name: "pasas (opcional)", quantity: "1", unit: "cucharada" },
      { name: "aceite", quantity: "1", unit: "cucharada (para el relleno)" },
      { name: "aceite para freír o para hornear", quantity: "suficiente", unit: "unidad" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Para el relleno: Calentar el aceite en una sartén a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir la carne molida y cocinar, desmenuzándola, hasta que esté dorada.",
      "Escurrir el exceso de grasa.",
      "Incorporar la salsa de tomate, comino, orégano, aceitunas y pasas (si se usan). Cocinar por unos minutos más.",
      "Sazonar con sal y pimienta al gusto. Dejar enfriar el relleno.",
      "Colocar una porción de relleno en el centro de cada disco de empanada.",
      "Doblar el disco por la mitad y sellar los bordes con un tenedor.",
      "Para freír: Calentar suficiente aceite en una sartén a fuego medio-alto y freír las empanadas hasta que estén doradas por ambos lados.",
      "Para hornear: Colocar las empanadas en una bandeja para hornear y hornear a 180°C por 15-20 minutos, o hasta que estén doradas.",
      "Servir calientes.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Pasta con Vegetales (Internacional, Vegetariano)",
    ingredients: [
      { name: "pasta corta (fusilli, penne)", quantity: "200", unit: "gramos" },
      {
        name: "tomates cherry",
        quantity: "150",
        unit: "gramos partidos por la mitad",
      },
      { name: "pepino", quantity: "1/2", unit: "unidad en cubos" },
      { name: "pimiento de colores", quantity: "1", unit: "unidad en cubos" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      { name: "aceitunas negras", quantity: "1/4", unit: "taza en rodajas" },
      { name: "aderezo italiano o vinagreta", quantity: "1/4", unit: "taza" },
      { name: "perejil fresco picado", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Cocer la pasta en agua hirviendo con sal según las instrucciones del paquete. Escurrir y enjuagar con agua fría para detener la cocción.",
      "En un bol grande, combinar la pasta cocida y enfriada con los tomates cherry, pepino, pimiento, cebolla roja y aceitunas negras.",
      "Verter el aderezo sobre la ensalada.",
      "Añadir el perejil picado.",
      "Mezclar bien para cubrir todos los ingredientes.",
      "Sazonar con sal y pimienta al gusto.",
      "Refrigerar por al menos 30 minutos antes de servir para que los sabores se mezclen.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Pescado (Cubana)",
    ingredients: [
      {
        name: "pescado (cabeza y espinas de pescado blanco)",
        quantity: "500",
        unit: "gramos",
      },
      {
        name: "filetes de pescado blanco",
        quantity: "200",
        unit: "gramos en trozos",
      },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento verde", quantity: "1/2", unit: "unidad" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "tomate", quantity: "2", unit: "unidades" },
      { name: "papas", quantity: "1", unit: "mediana en cubos" },
      { name: "zanahoria", quantity: "1", unit: "unidad en rodajas" },
      { name: "caldo de pescado o agua", quantity: "1.5", unit: "litros" },
      { name: "vino seco", quantity: "1/4", unit: "taza" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla grande, hacer un caldo hirviendo las cabezas y espinas de pescado con un trozo de cebolla, laurel y sal por unos 20 minutos. Colar el caldo y desechar los sólidos.",
      "En la misma olla (limpia), calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla picada, pimiento y ajo hasta que estén transparentes.",
      "Añadir los tomates picados y cocinar por unos minutos.",
      "Verter el caldo de pescado colado y el vino seco.",
      "Llevar a ebullición, luego reducir el fuego y añadir las papas y zanahoria.",
      "Cocinar por 15-20 minutos, o hasta que las verduras estén tiernas.",
      "Incorporar los trozos de filete de pescado y cocinar por 5-7 minutos más, o hasta que el pescado esté cocido.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz con Vegetales (Vegetariano, Bajo en Grasas)",
    ingredients: [
      { name: "arroz blanco", quantity: "1", unit: "taza" },
      { name: "agua o caldo de verduras", quantity: "2", unit: "tazas" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "pimiento de colores", quantity: "1", unit: "unidad picado" },
      { name: "zanahoria", quantity: "1", unit: "unidad en cubos pequeños" },
      { name: "chícharos (guisantes)", quantity: "1/2", unit: "taza" },
      { name: "maíz tierno (granos)", quantity: "1/2", unit: "taza" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir el arroz crudo y el comino. Revolver por 1 minuto.",
      "Incorporar la zanahoria, chícharos y maíz.",
      "Verter el agua o caldo. Sazonar con sal y pimienta al gusto.",
      "Llevar a ebullición, luego reducir el fuego al mínimo, tapar y cocinar por 15-20 minutos, o hasta que el arroz haya absorbido todo el líquido y esté tierno.",
      "Dejar reposar tapado por 5 minutos antes de servir.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Pollo (Alto en Proteínas)",
    ingredients: [
      {
        name: "pechuga de pollo cocida y desmenuzada",
        quantity: "1",
        unit: "unidad",
      },
      { name: "apio", quantity: "1", unit: "tallo picado" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      { name: "mayonesa", quantity: "1/4", unit: "taza" },
      { name: "mostaza Dijon", quantity: "1", unit: "cucharadita" },
      { name: "jugo de limón", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "lechuga", quantity: "para servir", unit: "unidad" },
      { name: "pan o galletas (opcional)", quantity: "para acompañar", unit: "unidad" },
    ],
    instructions: [
      "En un bol mediano, combinar el pollo cocido y desmenuzado, apio picado y cebolla roja picada.",
      "En un bol pequeño, mezclar la mayonesa, mostaza Dijon y jugo de limón.",
      "Verter el aderezo sobre la mezcla de pollo.",
      "Sazonar con sal y pimienta al gusto.",
      "Mezclar bien para combinar todos los ingredientes.",
      "Servir sobre hojas de lechuga o con pan o galletas.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sándwich Vegetal (Sin Electricidad, Vegetariano, Bajo en Calorías)",
    ingredients: [
      { name: "pan integral o de molde", quantity: "2", unit: "rebanadas" },
      {
        name: "hummus o aguacate machacado",
        quantity: "2",
        unit: "cucharadas",
      },
      { name: "lechuga", quantity: "1", unit: "hoja" },
      { name: "tomate", quantity: "2", unit: "rodajas" },
      { name: "pepino", quantity: "3", unit: "rodajas finas" },
      {
        name: "pimiento (cualquier color)",
        quantity: "2",
        unit: "rodajas finas",
      },
      { name: "cebolla roja (opcional)", quantity: "muy finas rodajas", unit: "unidad" },
      { name: "sal", quantity: "una pizca", unit: "unidad" },
      { name: "pimienta", quantity: "una pizca", unit: "unidad" },
    ],
    instructions: [
      "Untar hummus o aguacate machacado en una rebanada de pan.",
      "Colocar la hoja de lechuga encima.",
      "Apilar las rodajas de tomate, pepino, pimiento y cebolla (si se usa).",
      "Sazonar ligeramente con sal y pimienta.",
      "Cubrir con la otra rebanada de pan.",
      "Cortar por la mitad si se desea y servir.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Fideos con Vegetales (Internacional, Bajo en Grasas)",
    ingredients: [
      {
        name: "fideos (cabello de ángel o finos)",
        quantity: "50",
        unit: "gramos",
      },
      { name: "caldo de pollo o verduras", quantity: "1", unit: "litro" },
      { name: "zanahoria", quantity: "1", unit: "unidad en rodajas finas" },
      {
        name: "calabacín (zapallo)",
        quantity: "1/2",
        unit: "unidad en cubos pequeños",
      },
      {
        name: "puerro (la parte blanca)",
        quantity: "1/2",
        unit: "unidad en rodajas finas",
      },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "perejil fresco picado", quantity: "1", unit: "cucharada" },
    ],
    instructions: [
      "En una olla, llevar el caldo a ebullición.",
      "Añadir la zanahoria, calabacín y puerro.",
      "Cocinar por 5-7 minutos, o hasta que los vegetales estén casi tiernos.",
      "Incorporar los fideos y cocinar según las instrucciones del paquete (generalmente 3-5 minutos).",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, espolvoreado con perejil picado.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz Frito con Huevo y Vegetales (Internacional, Estándar)",
    ingredients: [
      {
        name: "arroz blanco cocido (del día anterior)",
        quantity: "2",
        unit: "tazas",
      },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "zanahoria", quantity: "1/2", unit: "unidad en cubos pequeños" },
      { name: "chícharos (guisantes)", quantity: "1/4", unit: "taza" },
      {
        name: "cebolla verde (cebolleta)",
        quantity: "2",
        unit: "tallos picados",
      },
      { name: "salsa de soja", quantity: "2", unit: "cucharadas" },
      { name: "aceite vegetal", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "una pizca (opcional)", unit: "unidad" },
    ],
    instructions: [
      "En un bol pequeño, batir los huevos con una pizca de sal (opcional).",
      "Calentar 1 cucharada de aceite vegetal en un wok o sartén grande a fuego medio-alto.",
      "Verter los huevos batidos y cocinar, revolviendo, hasta que estén revueltos. Retirar de la sartén y reservar.",
      "Añadir la cucharada restante de aceite a la sartén.",
      "Sofreír la zanahoria y los chícharos por 2-3 minutos.",
      "Incorporar el arroz cocido y cocinar, revolviendo constantemente, por 3-5 minutos, hasta que el arroz esté caliente.",
      "Añadir la salsa de soja y la cebolla verde picada. Mezclar bien.",
      "Regresar los huevos revueltos a la sartén y combinar con el arroz.",
      "Servir caliente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Ensalada Caprese (Internacional, Vegetariano, Bajo en Carbohidratos)",
    ingredients: [
      {
        name: "tomates maduros",
        quantity: "2",
        unit: "unidades en rodajas gruesas",
      },
      {
        name: "mozzarella fresca (bola)",
        quantity: "200",
        unit: "gramos en rodajas gruesas",
      },
      {
        name: "hojas de albahaca fresca",
        quantity: "unas 10-15",
        unit: "unidades",
      },
      {
        name: "aceite de oliva virgen extra",
        quantity: "2",
        unit: "cucharadas",
      },
      {
        name: "glaseado balsámico (opcional)",
        quantity: "1",
        unit: "cucharada",
      },
      { name: "sal", quantity: "una pizca", unit: "unidad" },
      { name: "pimienta negra recién molida", quantity: "una pizca", unit: "unidad" },
    ],
    instructions: [
      "En un plato o bandeja, alternar rodajas de tomate y mozzarella fresca.",
      "Colocar hojas de albahaca fresca entre las rodajas.",
      "Rociar generosamente con aceite de oliva virgen extra.",
      "Opcionalmente, rociar con glaseado balsámico.",
      "Sazonar con sal y pimienta negra recién molida.",
      "Servir inmediatamente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en carbohidratos",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Maíz (Cubana)",
    ingredients: [
      { name: "maíz tierno (granos)", quantity: "3", unit: "tazas" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "pimiento verde", quantity: "1/4", unit: "unidad picado" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "leche", quantity: "2", unit: "tazas" },
      { name: "caldo de pollo o verduras", quantity: "2", unit: "tazas" },
      { name: "mantequilla o aceite", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "cilantro fresco picado (para decorar)", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla, derretir la mantequilla o calentar el aceite a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir los granos de maíz y cocinar por unos minutos.",
      "Verter el caldo y la leche. Llevar a ebullición suave.",
      "Reducir el fuego y cocinar a fuego lento por 10-15 minutos, o hasta que el maíz esté tierno.",
      "Opcionalmente, triturar una parte de la sopa con una batidora de mano para espesarla.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, decorada con cilantro picado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz a la Marinera (Cubana)",
    ingredients: [
      { name: "arroz blanco", quantity: "2", unit: "tazas" },
      {
        name: "mariscos variados (gambas, calamares, mejillones)",
        quantity: "500",
        unit: "gramos limpios",
      },
      { name: "cebolla", quantity: "1", unit: "mediana picada" },
      { name: "pimiento rojo", quantity: "1", unit: "mediano picado" },
      { name: "ajo", quantity: "4", unit: "dientes picados" },
      { name: "tomate triturado", quantity: "1/2", unit: "taza" },
      { name: "vino blanco seco", quantity: "1/2", unit: "taza" },
      { name: "caldo de pescado o marisco", quantity: "4", unit: "tazas" },
      { name: "azafrán o colorante alimentario", quantity: "unas hebras o 1/2 cucharadita", unit: "unidad" },
      { name: "aceite de oliva", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "perejil fresco picado", quantity: "para decorar", unit: "unidad" },
    ],
    instructions: [
      "En una cazuela grande o paellera, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir el tomate triturado y cocinar por unos minutos.",
      "Incorporar los mariscos (excepto las gambas si son pequeñas y se cocinan rápido) y cocinar por 2-3 minutos.",
      "Verter el vino blanco y dejar que se evapore el alcohol.",
      "Añadir el arroz y remover para que se impregne de los sabores.",
      "Verter el caldo caliente con el azafrán o colorante. Asegurarse de que el caldo cubra el arroz.",
      "Sazonar con sal y pimienta al gusto.",
      "Llevar a ebullición, luego reducir el fuego a medio-bajo, tapar y cocinar por 15-20 minutos, o hasta que el arroz esté tierno y el líquido se haya absorbido. Añadir las gambas en los últimos 5-7 minutos si no se añadieron antes.",
      "Dejar reposar tapado por 5 minutos antes de servir.",
      "Servir caliente, decorado con perejil picado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Ensalada de Quinoa con Vegetales (Internacional, Vegetariano, Alto en Proteínas)",
    ingredients: [
      { name: "quinoa", quantity: "1", unit: "taza" },
      { name: "agua o caldo de verduras", quantity: "2", unit: "tazas" },
      { name: "pepino", quantity: "1/2", unit: "unidad en cubos pequeños" },
      {
        name: "tomates cherry",
        quantity: "150",
        unit: "gramos partidos por la mitad",
      },
      {
        name: "pimiento amarillo",
        quantity: "1/2",
        unit: "unidad en cubos pequeños",
      },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      { name: "perejil fresco", quantity: "2", unit: "cucharadas picado" },
      {
        name: "menta fresca (opcional)",
        quantity: "1",
        unit: "cucharada picada",
      },
      {
        name: "aceite de oliva virgen extra",
        quantity: "3",
        unit: "cucharadas",
      },
      { name: "jugo de limón", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla, enjuagar la quinoa bajo agua fría. Combinar la quinoa enjuagada con el agua o caldo. Llevar a ebullición.",
      "Reducir el fuego al mínimo, tapar y cocinar por 15 minutos, o hasta que la quinoa haya absorbido todo el líquido.",
      "Retirar del fuego y dejar reposar tapado por 5 minutos. Esponjar con un tenedor y dejar enfriar completamente.",
      "En un bol grande, combinar la quinoa enfriada con el pepino, tomates cherry, pimiento amarillo, cebolla roja, perejil y menta (si se usa).",
      "En un bol pequeño, batir el aceite de oliva y el jugo de limón. Sazonar con sal y pimienta al gusto.",
      "Verter el aderezo sobre la ensalada de quinoa.",
      "Mezclar suavemente para combinar.",
      "Servir a temperatura ambiente o fría.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Sopa de Vegetales (Sin Electricidad, Bajo en Calorías, Vegetariano)",
    ingredients: [
      {
        name: "variedad de vegetales (zanahoria, apio, calabacín, papas)",
        quantity: "4",
        unit: "tazas en cubos",
      },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "tomate triturado", quantity: "200", unit: "gramos" },
      { name: "caldo de verduras o agua", quantity: "1", unit: "litro" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "perejil fresco picado", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir los vegetales en cubos, tomate triturado y la hoja de laurel.",
      "Verter el caldo o agua. Llevar a ebullición.",
      "Reducir el fuego, tapar y cocinar a fuego lento por 20-25 minutos, o hasta que los vegetales estén tiernos.",
      "Retirar la hoja de laurel.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, espolvoreada con perejil picado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz Blanco con Huevo Frito y Plátano Maduro Frito (Cubana)",
    ingredients: [
      { name: "arroz blanco cocido", quantity: "1", unit: "taza" },
      { name: "huevo", quantity: "1", unit: "unidad" },
      { name: "plátano maduro", quantity: "1", unit: "unidad" },
      { name: "aceite para freír", quantity: "suficiente", unit: "unidad" },
      { name: "sal", quantity: "una pizca", unit: "unidad" },
    ],
    instructions: [
      "Cocinar el arroz blanco.",
      "Pelar el plátano maduro y cortarlo en rodajas diagonales.",
      "Calentar aceite en una sartén y freír las rodajas de plátano hasta que estén doradas. Retirar.",
      "En la misma sartén, freír el huevo hasta que la clara esté cuajada.",
      "Servir el arroz blanco caliente con el huevo frito encima y las rodajas de plátano maduro frito al lado. Añadir una pizca de sal al huevo si se desea.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Picadillo con Papas Fritas (Cubana)",
    ingredients: [
      { name: "carne molida", quantity: "300", unit: "gramos" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "pimiento", quantity: "1/4", unit: "unidad picado" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "salsa de tomate", quantity: "1/4", unit: "taza" },
      { name: "aceitunas verdes picadas", quantity: "2", unit: "cucharadas" },
      { name: "pasas (opcional)", quantity: "1", unit: "cucharada" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "orégano", quantity: "1/4", unit: "cucharadita" },
      { name: "aceite", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "papas", quantity: "2", unit: "medianas para freír" },
      { name: "aceite para freír papas", quantity: "suficiente", unit: "unidad" },
    ],
    instructions: [
      "Para el picadillo: Calentar el aceite en una sartén a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir la carne molida y cocinar, desmenuzándola, hasta que esté dorada.",
      "Escurrir el exceso de grasa.",
      "Incorporar la salsa de tomate, comino, orégano, aceitunas y pasas (si se usan). Cocinar por unos minutos más.",
      "Sazonar con sal y pimienta al gusto.",
      "Para las papas fritas: Pelar las papas y cortarlas en bastones.",
      "Calentar suficiente aceite en una sartén o freidora a fuego medio-alto.",
      "Freír las papas en tandas hasta que estén doradas y crujientes. Retirar y escurrir sobre papel absorbente. Sazonar con sal.",
      "Servir el picadillo caliente acompañado de las papas fritas.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Ensalada de Lentejas (Sin Electricidad, Vegetariano, Alto en Proteínas)",
    ingredients: [
      { name: "lentejas cocidas y enfriadas", quantity: "1.5", unit: "tazas" },
      { name: "tomate", quantity: "1", unit: "unidad en cubos" },
      { name: "pepino", quantity: "1/2", unit: "unidad en cubos" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      { name: "pimiento verde", quantity: "1/4", unit: "unidad en cubos" },
      { name: "perejil fresco", quantity: "2", unit: "cucharadas picado" },
      {
        name: "aceite de oliva virgen extra",
        quantity: "2",
        unit: "cucharadas",
      },
      { name: "vinagre de manzana o limón", quantity: "1", unit: "cucharada" },
      { name: "comino molido", quantity: "1/4", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol grande, combinar las lentejas cocidas, tomate, pepino, cebolla roja, pimiento verde y perejil.",
      "En un bol pequeño, batir el aceite de oliva, vinagre, comino, sal y pimienta para hacer el aderezo.",
      "Verter el aderezo sobre la ensalada de lentejas.",
      "Mezclar suavemente para combinar.",
      "Servir a temperatura ambiente o fría.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Garbanzos (Cubana, Bajo en Grasas)",
    ingredients: [
      { name: "garbanzos secos", quantity: "250", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "mediana picada" },
      { name: "pimiento rojo", quantity: "1/2", unit: "unidad picado" },
      { name: "ajo", quantity: "3", unit: "dientes picados" },
      { name: "chorizo (opcional)", quantity: "50", unit: "gramos en rodajas" },
      { name: "tomate triturado", quantity: "1/4", unit: "taza" },
      { name: "caldo de verduras o agua", quantity: "1.5", unit: "litros" },
      { name: "comino", quantity: "1", unit: "cucharadita" },
      { name: "pimentón dulce", quantity: "1/2", unit: "cucharadita" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Remojar los garbanzos en agua durante la noche.",
      "Escurrir y enjuagar los garbanzos.",
      "En una olla grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Si se usa chorizo, añadirlo y cocinar por unos minutos.",
      "Incorporar el tomate triturado, comino y pimentón. Cocinar por 1 minuto.",
      "Añadir los garbanzos, el caldo o agua y la hoja de laurel.",
      "Llevar a ebullición, luego reducir el fuego y cocinar a fuego lento por 1.5 - 2 horas, o hasta que los garbanzos estén muy tiernos.",
      "Retirar la hoja de laurel. Sazonar con sal y pimienta al gusto.",
      "Servir caliente.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Almuerzo",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz con Atún y Vegetales (Sin Electricidad)",
    ingredients: [
      {
        name: "arroz blanco cocido y enfriado",
        quantity: "1.5",
        unit: "tazas",
      },
      {
        name: "atún en lata (en agua o aceite)",
        quantity: "1",
        unit: "lata escurrida",
      },
      {
        name: "maíz tierno (en lata)",
        quantity: "1/2",
        unit: "taza escurrido",
      },
      {
        name: "chícharos (guisantes en lata)",
        quantity: "1/2",
        unit: "taza escurridos",
      },
      { name: "pimiento rojo", quantity: "1/4", unit: "unidad picado pequeño" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      { name: "mayonesa", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol grande, combinar el arroz cocido y enfriado, el atún desmenuzado, maíz, chícharos, pimiento rojo y cebolla roja.",
      "Añadir la mayonesa, sal y pimienta al gusto.",
      "Mezclar bien para combinar todos los ingredientes.",
      "Servir frío.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Pollo y Arroz (Internacional, Bajo en Grasas)",
    ingredients: [
      {
        name: "pollo (muslos o contramuslos)",
        quantity: "2",
        unit: "unidades",
      },
      { name: "arroz blanco", quantity: "1/2", unit: "taza" },
      { name: "zanahorias", quantity: "1", unit: "unidad en rodajas" },
      { name: "apio", quantity: "1", unit: "tallo en rodajas" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "caldo de pollo", quantity: "1.5", unit: "litros" },
      { name: "perejil fresco", quantity: "1", unit: "cucharada picado" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir el pollo, zanahorias y apio.",
      "Verter el caldo de pollo. Llevar a ebullición.",
      "Reducir el fuego, tapar y cocinar a fuego lento por 20 minutos.",
      "Añadir el arroz y cocinar por 15-20 minutos más, o hasta que el arroz y el pollo estén cocidos.",
      "Retirar el pollo, desmenuzarlo y regresarlo a la sopa.",
      "Añadir el perejil picado.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Col (Sin Electricidad, Bajo en Calorías)",
    ingredients: [
      {
        name: "col blanca (repollo)",
        quantity: "1/2",
        unit: "unidad rallada finamente",
      },
      { name: "zanahoria", quantity: "1", unit: "unidad rallada" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad rallada finamente (opcional)",
      },
      { name: "mayonesa", quantity: "2", unit: "cucharadas" },
      { name: "vinagre blanco", quantity: "1", unit: "cucharada" },
      { name: "azúcar", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol grande, combinar la col rallada, zanahoria rallada y cebolla roja rallada (si se usa).",
      "En un bol pequeño, mezclar la mayonesa, vinagre blanco, azúcar, sal y pimienta para hacer el aderezo.",
      "Verter el aderezo sobre los vegetales rallados.",
      "Mezclar bien para cubrir todos los ingredientes.",
      "Refrigerar por al menos 30 minutos antes de servir para que los sabores se mezclen y la col se ablande ligeramente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Sopa de Tomate y Arroz (Internacional, Vegetariano, Bajo en Grasas)",
    ingredients: [
      { name: "tomate triturado", quantity: "400", unit: "gramos" },
      { name: "arroz blanco", quantity: "1/4", unit: "taza" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "caldo de verduras o agua", quantity: "750", unit: "ml" },
      { name: "orégano seco", quantity: "1/2", unit: "cucharadita" },
      { name: "albahaca seca", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir el tomate triturado, orégano y albahaca. Cocinar por unos minutos.",
      "Incorporar el arroz y el caldo o agua.",
      "Llevar a ebullición, luego reducir el fuego y cocinar a fuego lento por 15-20 minutos, o hasta que el arroz esté tierno.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Almuerzo",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
];
