import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de cenas cubanas e internacionales
 */
export const CENAS: Recipe[] = [
  // Recetas existentes (manteniendo las originales)
  {
    id: generateId(),
    title: "Tortilla de Papas Cubana",
    ingredients: [
      { name: "papas", quantity: "3", unit: "medianas" },
      { name: "huevos", quantity: "4", unit: "unidades" },
      { name: "cebolla", quantity: "1", unit: "pequeña" },
      { name: "aceite", quantity: "4", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Pelar y cortar las papas en rodajas finas",
      "Picar la cebolla en trozos pequeños",
      "Calentar el aceite en una sartén y freír las papas a fuego medio-bajo",
      "Añadir la cebolla y seguir cocinando hasta que las papas estén tiernas",
      "Batir los huevos en un recipiente aparte, añadir sal",
      "Escurrir el exceso de aceite de las papas y añadirlas a los huevos",
      "Mezclar bien y verter todo de nuevo en la sartén",
      "Cocinar a fuego medio-bajo hasta que la base esté cuajada",
      "Dar la vuelta a la tortilla con ayuda de un plato y cocinar el otro lado",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Vegetales con Limón (Sin Electricidad)",
    ingredients: [
      { name: "lechuga", quantity: "1", unit: "pequeña" },
      { name: "tomate", quantity: "2", unit: "unidades" },
      { name: "pepino", quantity: "1", unit: "unidad" },
      { name: "zanahoria", quantity: "1", unit: "unidad" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Lavar y trocear la lechuga en trozos pequeños",
      "Cortar los tomates y el pepino en cubos",
      "Rallar la zanahoria",
      "Mezclar todos los vegetales en un recipiente grande",
      "Aliñar con jugo de limón, aceite y sal al gusto",
      "Mezclar bien antes de servir",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pollo a la Plancha con Limón",
    ingredients: [
      { name: "pechugas de pollo", quantity: "2", unit: "unidades" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "ajo", quantity: "2", unit: "dientes" },
      { name: "orégano", quantity: "1", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "pimienta", quantity: "1/2", unit: "cucharadita" },
    ],
    instructions: [
      "Aplanar ligeramente las pechugas de pollo para que tengan un grosor uniforme",
      "Mezclar el jugo de limón, ajo picado, orégano, sal y pimienta en un recipiente",
      "Marinar el pollo en esta mezcla por al menos 15 minutos",
      "Calentar una plancha o sartén con aceite de oliva",
      "Cocinar el pollo a fuego medio-alto, aproximadamente 5-6 minutos por cada lado",
      "Verificar que esté bien cocido y servir caliente con rodajas de limón",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Picadillo Cubano",
    ingredients: [
      { name: "carne molida", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento", quantity: "1", unit: "mediano" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "salsa de tomate", quantity: "1/4", unit: "taza" },
      { name: "aceitunas verdes", quantity: "1/4", unit: "taza" },
      { name: "pasas", quantity: "1/4", unit: "taza" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "orégano", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "pimienta", quantity: "1/4", unit: "cucharadita" },
    ],
    instructions: [
      "Picar finamente la cebolla, el pimiento y el ajo",
      "Calentar el aceite en una sartén grande y sofreír la cebolla y el pimiento",
      "Añadir el ajo y cocinar por 1 minuto más",
      "Agregar la carne molida y cocinar hasta que pierda el color rosado",
      "Añadir el comino, orégano, sal y pimienta",
      "Incorporar la salsa de tomate y mezclar bien",
      "Añadir las aceitunas picadas y las pasas",
      "Cocinar a fuego medio-bajo por 15-20 minutos hasta que los sabores se integren",
      "Servir caliente con arroz blanco",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Espaguetis con Salsa de Tomate Casera",
    ingredients: [
      { name: "espaguetis", quantity: "250", unit: "gramos" },
      { name: "tomates", quantity: "4", unit: "unidades" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "ajo", quantity: "2", unit: "dientes" },
      { name: "albahaca", quantity: "8", unit: "hojas" },
      { name: "aceite de oliva", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Hervir agua con sal en una olla grande",
      "Cocer los espaguetis según las instrucciones del paquete",
      "Mientras tanto, pelar y picar la cebolla y el ajo",
      "Cortar los tomates en cubos",
      "En una sartén grande, calentar el aceite y sofreír la cebolla y el ajo",
      "Añadir los tomates y cocinar a fuego medio hasta que se forme una salsa",
      "Triturar ligeramente con un tenedor para obtener una textura semi-espesa",
      "Añadir la albahaca picada al final",
      "Mezclar los espaguetis con la salsa y servir caliente",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tortilla de Papa y Cebolla (Sin Electricidad)",
    ingredients: [
      { name: "papas", quantity: "2", unit: "medianas" },
      { name: "cebolla", quantity: "1", unit: "pequeña" },
      { name: "huevos", quantity: "4", unit: "unidades" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Pelar y cortar las papas en rodajas finas",
      "Picar la cebolla en juliana",
      "Calentar el aceite en una sartén y freír las papas y la cebolla a fuego medio-bajo",
      "Batir los huevos en un recipiente y añadir sal",
      "Cuando las papas estén blandas, escurrir el exceso de aceite",
      "Mezclar las papas y cebolla con los huevos batidos",
      "Verter la mezcla en la sartén y cocinar a fuego medio-bajo",
      "Cuando la base esté cuajada, dar la vuelta con ayuda de un plato",
      "Cocinar el otro lado y servir caliente o a temperatura ambiente",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Bajo en carbohidratos",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Salmón al Horno con Espárragos (Internacional)",
    ingredients: [
      { name: "filetes de salmón", quantity: "2", unit: "unidades" },
      { name: "espárragos", quantity: "250", unit: "gramos" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "ajo en polvo", quantity: "1/2", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Precalentar el horno a 200°C.",
      "Lavar y cortar la parte leñosa de los espárragos.",
      "En una bandeja para hornear, colocar los espárragos y rociar con un poco de aceite de oliva, sal y pimienta.",
      "Colocar los filetes de salmón sobre los espárragos.",
      "Rociar el salmón con el resto del aceite de oliva, jugo de limón, ajo en polvo, sal y pimienta.",
      "Hornear por 12-15 minutos, o hasta que el salmón esté cocido y los espárragos tiernos.",
      "Servir caliente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Curry de Garbanzos y Espinacas (Internacional)",
    ingredients: [
      { name: "garbanzos cocidos", quantity: "400", unit: "gramos" },
      { name: "espinacas frescas", quantity: "200", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "ajo", quantity: "2", unit: "dientes" },
      { name: "jengibre fresco", quantity: "1", unit: "cucharadita rallada" },
      { name: "tomate triturado", quantity: "400", unit: "gramos" },
      { name: "leche de coco", quantity: "400", unit: "ml" },
      { name: "pasta de curry rojo", quantity: "2", unit: "cucharadas" },
      { name: "aceite de coco o vegetal", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "arroz basmati", quantity: "para acompañar", unit: "unidad" },
    ],
    instructions: [
      "Picar finamente la cebolla y el ajo.",
      "Calentar el aceite en una olla grande a fuego medio.",
      "Sofreír la cebolla hasta que esté transparente.",
      "Añadir el ajo y el jengibre, cocinar por 1 minuto más.",
      "Incorporar la pasta de curry rojo y cocinar por 2 minutos, removiendo constantemente.",
      "Agregar el tomate triturado y cocinar por 5 minutos.",
      "Añadir la leche de coco y los garbanzos cocidos.",
      "Llevar a ebullición, luego reducir el fuego y cocinar a fuego lento por 10-15 minutos.",
      "Añadir las espinacas y cocinar hasta que se marchiten.",
      "Sazonar con sal al gusto.",
      "Servir caliente con arroz basmati.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pescado Frito con Mojo Cubano",
    ingredients: [
      { name: "pescado entero (pargo o similar)", quantity: "1", unit: "kg" },
      { name: "ajo", quantity: "6", unit: "dientes" },
      { name: "cebolla", quantity: "1/2", unit: "unidad" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "naranja agria", quantity: "1", unit: "unidad" },
      { name: "aceite de oliva", quantity: "1/4", unit: "taza" },
      { name: "aceite para freír", quantity: "suficiente", unit: "unidad" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Limpiar bien el pescado y hacer cortes diagonales en ambos lados.",
      "Sazonar el pescado por dentro y por fuera con sal y pimienta.",
      "Para el mojo: picar el ajo y la cebolla finamente.",
      "Calentar el aceite de oliva en una sartén pequeña.",
      "Añadir el ajo y la cebolla, cocinar a fuego lento sin que se doren.",
      "Exprimir el limón y la naranja agria, añadir el jugo a la sartén.",
      "Cocinar por 2 minutos más. Reservar.",
      "Calentar suficiente aceite para freír en una sartén grande o freidora a fuego medio-alto.",
      "Freír el pescado entero hasta que esté dorado y cocido por dentro, volteándolo una vez.",
      "Retirar el pescado y colocar sobre papel absorbente.",
      "Servir el pescado frito caliente y rociar generosamente con el mojo criollo.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz a la Cubana (Fácil, Estándar)",
    ingredients: [
      { name: "arroz blanco cocido", quantity: "1", unit: "taza" },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "plátano maduro", quantity: "1", unit: "unidad" },
      { name: "salsa de tomate", quantity: "1/4", unit: "taza" },
      { name: "aceite", quantity: "para freír", unit: "unidad" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Cocinar el arroz blanco según las instrucciones del paquete.",
      "Pelar el plátano maduro y cortarlo en rodajas diagonales.",
      "Calentar aceite en una sartén y freír las rodajas de plátano hasta que estén doradas por ambos lados. Retirar y reservar.",
      "En la misma sartén, freír los huevos al gusto (estrellados son tradicionales).",
      "Calentar la salsa de tomate en una olla pequeña.",
      "En un plato, colocar una porción de arroz blanco, un huevo frito, las rodajas de plátano frito y cubrir con salsa de tomate caliente.",
      "Servir inmediatamente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Lasaña de Carne (Internacional, Avanzada)",
    ingredients: [
      { name: "láminas de lasaña", quantity: "12", unit: "unidades" },
      { name: "carne molida de res", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "ajo", quantity: "2", unit: "dientes" },
      { name: "tomate triturado", quantity: "800", unit: "gramos" },
      { name: "pasta de tomate", quantity: "2", unit: "cucharadas" },
      { name: "orégano seco", quantity: "1", unit: "cucharadita" },
      { name: "albahaca seca", quantity: "1", unit: "cucharadita" },
      { name: "azúcar", quantity: "1", unit: "cucharadita (opcional)" },
      { name: "queso ricotta", quantity: "500", unit: "gramos" },
      { name: "huevo", quantity: "1", unit: "unidad" },
      { name: "queso parmesano rallado", quantity: "1/2", unit: "taza" },
      { name: "queso mozzarella rallado", quantity: "2", unit: "tazas" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Precalentar el horno a 180°C.",
      "Para la salsa de carne: Calentar el aceite de oliva en una olla grande a fuego medio.",
      "Sofreír la cebolla picada hasta que esté transparente. Añadir el ajo picado y cocinar por 1 minuto.",
      "Agregar la carne molida y cocinar, desmenuzándola, hasta que esté dorada.",
      "Escurrir el exceso de grasa.",
      "Incorporar el tomate triturado, pasta de tomate, orégano, albahaca, azúcar (si se usa), sal y pimienta.",
      "Cocinar a fuego lento por al menos 30 minutos, revolviendo ocasionalmente.",
      "Mientras tanto, cocinar las láminas de lasaña según las instrucciones del paquete. Escurrir y reservar.",
      "En un bol mediano, mezclar el queso ricotta, el huevo y 1/4 taza de queso parmesano. Sazonar con sal y pimienta.",
      "Para armar la lasaña: En el fondo de un molde para hornear rectangular, extender una capa fina de salsa de carne.",
      "Colocar una capa de láminas de lasaña.",
      "Extender la mitad de la mezcla de ricotta sobre las láminas.",
      "Cubrir con una capa de salsa de carne.",
      "Espolvorear con 1 taza de queso mozzarella.",
      "Repetir las capas: láminas de lasaña, el resto de la mezcla de ricotta, salsa de carne y el resto del queso mozzarella.",
      "Espolvorear con el resto del queso parmesano.",
      "Cubrir el molde con papel de aluminio y hornear por 25 minutos.",
      "Retirar el papel de aluminio y hornear por 10-15 minutos más, o hasta que el queso esté burbujeante y dorado.",
      "Dejar reposar por 10-15 minutos antes de cortar y servir.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Avanzada",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Tomate Fría (Sin Electricidad, Bajo en Calorías)",
    ingredients: [
      { name: "tomates maduros", quantity: "5", unit: "unidades" },
      { name: "pepino", quantity: "1/2", unit: "unidad" },
      { name: "pimiento rojo", quantity: "1/2", unit: "unidad" },
      { name: "cebolla roja", quantity: "1/4", unit: "unidad" },
      { name: "ajo", quantity: "1", unit: "diente" },
      {
        name: "aceite de oliva virgen extra",
        quantity: "2",
        unit: "cucharadas",
      },
      { name: "vinagre de vino tinto", quantity: "1", unit: "cucharada" },
      { name: "agua fría", quantity: "1/2", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Lavar y trocear los tomates, pepino, pimiento y cebolla.",
      "Pelar el ajo.",
      "En un recipiente grande, combinar todos los vegetales troceados y el ajo.",
      "Con un mortero o machacador, triturar los ingredientes hasta obtener una pasta lo más fina posible. (Nota: La textura no será tan suave como con una batidora).",
      "Añadir el aceite de oliva, el vinagre, el agua fría, sal y pimienta.",
      "Mezclar bien.",
      "Probar y ajustar la sazón si es necesario.",
      "Servir frío.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  // --- 15 Recetas adicionales para Cena ---
  {
    id: generateId(),
    title: "Cerdo Asado Cubano (Lechón Asado)",
    ingredients: [
      { name: "pernil de cerdo (con piel)", quantity: "2", unit: "kg" },
      { name: "ajo", quantity: "10", unit: "dientes" },
      { name: "cebolla", quantity: "1", unit: "grande" },
      { name: "naranja agria", quantity: "1", unit: "taza de jugo" },
      { name: "orégano seco", quantity: "2", unit: "cucharadas" },
      { name: "comino molido", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "aceite de oliva", quantity: "1/4", unit: "taza" },
    ],
    instructions: [
      "Hacer cortes profundos en la piel del pernil con un cuchillo afilado.",
      "En un mortero, machacar el ajo con sal, orégano y comino hasta formar una pasta.",
      "En un bol, mezclar la pasta de ajo con el jugo de naranja agria, pimienta y aceite de oliva.",
      "Frotar esta marinada por todo el pernil, asegurándose de que penetre en los cortes. Marinar en el refrigerador por al menos 4 horas, o preferiblemente toda la noche.",
      "Precalentar el horno a 160°C.",
      "Colocar el pernil en una bandeja para hornear, con la piel hacia arriba.",
      "Hornear por 3-4 horas, o hasta que la carne esté muy tierna. Rociar con los jugos de la bandeja ocasionalmente.",
      "Subir la temperatura del horno a 220°C en los últimos 20-30 minutos para que la piel se ponga crujiente (chicharrón). Vigilar para que no se queme.",
      "Dejar reposar por 15-20 minutos antes de cortar y servir.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Avanzada",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Vaca Frita Cubana",
    ingredients: [
      { name: "falda de res", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "grande en julianas" },
      { name: "ajo", quantity: "4", unit: "dientes picados" },
      { name: "naranja agria", quantity: "1/2", unit: "taza de jugo" },
      { name: "comino molido", quantity: "1", unit: "cucharadita" },
      { name: "orégano seco", quantity: "1", unit: "cucharadita" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "aceite vegetal", quantity: "1/4", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla, cocinar la falda de res en agua con sal y la hoja de laurel hasta que esté muy tierna (aproximadamente 1.5 - 2 horas).",
      "Retirar la carne y desmenuzarla con dos tenedores.",
      "En un bol, mezclar el jugo de naranja agria con el ajo picado, comino, orégano, sal y pimienta.",
      "Marinar la carne desmenuzada en esta mezcla por al menos 30 minutos.",
      "En una sartén grande, calentar el aceite vegetal a fuego medio-alto.",
      "Añadir la carne marinada y cocinar, extendiéndola en una capa, hasta que esté dorada y crujiente por los bordes.",
      "Añadir las julianas de cebolla y cocinar, revolviendo ocasionalmente, hasta que la cebolla esté dorada y suave.",
      "Servir caliente.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Costillas de Cerdo Fritas (Cubana)",
    ingredients: [
      {
        name: "costillas de cerdo (cortadas individualmente)",
        quantity: "1",
        unit: "kg",
      },
      { name: "ajo", quantity: "6", unit: "dientes machacados" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "comino molido", quantity: "1", unit: "cucharadita" },
      { name: "aceite para freír", quantity: "suficiente", unit: "unidad" },
    ],
    instructions: [
      "Sazonar las costillas de cerdo con el ajo machacado, sal, pimienta y comino.",
      "Dejar marinar por al menos 30 minutos.",
      "Calentar suficiente aceite para freír en una sartén profunda o freidora a fuego medio-alto.",
      "Freír las costillas en tandas hasta que estén doradas, crujientes y cocidas por dentro (aproximadamente 8-10 minutos por tanda).",
      "Retirar y colocar sobre papel absorbente para eliminar el exceso de grasa.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pollo Frito a la Sureña (Internacional, Alto en Proteínas)",
    ingredients: [
      {
        name: "piezas de pollo (muslos, contramuslos, pechugas)",
        quantity: "1",
        unit: "kg",
      },
      { name: "suero de leche (buttermilk)", quantity: "2", unit: "tazas" },
      { name: "harina de trigo", quantity: "2", unit: "tazas" },
      { name: "pimentón", quantity: "1", unit: "cucharada" },
      { name: "ajo en polvo", quantity: "1", unit: "cucharadita" },
      { name: "cebolla en polvo", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "2", unit: "cucharaditas" },
      { name: "pimienta negra", quantity: "1", unit: "cucharadita" },
      {
        name: "aceite vegetal para freír",
        quantity: "suficiente",
        unit: "unidad",
      },
    ],
    instructions: [
      "Colocar las piezas de pollo en un bol grande y verter el suero de leche. Asegurarse de que el pollo esté bien cubierto. Marinar en el refrigerador por al menos 1 hora.",
      "En un plato hondo, mezclar la harina, pimentón, ajo en polvo, cebolla en polvo, sal y pimienta.",
      "Retirar las piezas de pollo del suero de leche, dejando que escurra el exceso.",
      "Pasar cada pieza de pollo por la mezcla de harina, cubriendo bien por todos lados.",
      "Calentar suficiente aceite vegetal en una sartén grande y profunda o freidora a 175°C.",
      "Freír el pollo en tandas, sin sobrecargar la sartén, por 6-10 minutos por cada lado (el tiempo varía según el tamaño de la pieza), hasta que esté dorado, crujiente y cocido por dentro (la temperatura interna debe ser 75°C).",
      "Retirar el pollo frito y colocar sobre una rejilla para escurrir el exceso de aceite.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tacos de Pescado (Internacional, Estándar)",
    ingredients: [
      {
        name: "filetes de pescado blanco (tilapia, bacalao)",
        quantity: "400",
        unit: "gramos",
      },
      { name: "tortillas de maíz o trigo", quantity: "8", unit: "unidades" },
      { name: "col rallada", quantity: "1", unit: "taza" },
      {
        name: "pico de gallo (tomate, cebolla, cilantro, jalapeño, limón)",
        quantity: "1",
        unit: "taza",
      },
      { name: "crema agria o yogur griego", quantity: "1/4", unit: "taza" },
      { name: "jugo de limón", quantity: "1", unit: "unidad" },
      { name: "chile en polvo", quantity: "1", unit: "cucharadita" },
      { name: "comino molido", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite vegetal", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Sazonar los filetes de pescado con chile en polvo, comino, sal y pimienta.",
      "Calentar el aceite vegetal en una sartén a fuego medio-alto.",
      "Cocinar el pescado por 3-4 minutos por cada lado, o hasta que esté cocido y se desmenuce fácilmente.",
      "Mientras tanto, calentar las tortillas en un comal o sartén seca.",
      "Para armar los tacos: Colocar una porción de pescado desmenuzado en cada tortilla.",
      "Cubrir con col rallada, pico de gallo y una cucharada de crema agria o yogur.",
      "Rociar con jugo de limón adicional si se desea.",
      "Servir inmediatamente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Chiles Rellenos de Queso (Internacional, Vegetariano)",
    ingredients: [
      { name: "chiles poblanos grandes", quantity: "4", unit: "unidades" },
      {
        name: "queso ( Oaxaca, mozzarella, o una mezcla)",
        quantity: "200",
        unit: "gramos rallado",
      },
      { name: "harina de trigo", quantity: "1/4", unit: "taza" },
      {
        name: "huevos",
        quantity: "2",
        unit: "unidades (separadas yemas y claras)",
      },
      { name: "aceite vegetal para freír", quantity: "suficiente", unit: "unidad" },
      { name: "salsa de tomate (para servir)", quantity: "al gusto", unit: "unidad" },
      { name: "sal", quantity: "una pizca", unit: "unidad" },
    ],
    instructions: [
      "Asar los chiles poblanos directamente sobre la llama de la estufa o bajo el grill del horno hasta que la piel esté carbonizada por todos lados.",
      "Colocar los chiles asados en una bolsa de plástico o recipiente tapado por 10-15 minutos para que suden.",
      "Retirar la piel quemada de los chiles. Hacer un corte a lo largo de un lado de cada chile y retirar las semillas y venas (con cuidado).",
      "Rellenar cada chile con queso rallado.",
      "Pasar cada chile relleno por harina, cubriendo bien.",
      "En un bol, batir las claras de huevo con una pizca de sal hasta que formen picos firmes.",
      "En otro bol, batir las yemas de huevo.",
      "Incorporar suavemente las yemas a las claras montadas con movimientos envolventes.",
      "Calentar suficiente aceite vegetal en una sartén a fuego medio-alto.",
      "Sosteniendo cada chile relleno, sumergirlo en la mezcla de huevo batido, cubriendo completamente.",
      "Freír los chiles rellenos en el aceite caliente hasta que estén dorados por todos lados.",
      "Retirar y colocar sobre papel absorbente.",
      "Servir caliente, bañados en salsa de tomate.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Cebolla Francesa (Internacional, Estándar)",
    ingredients: [
      {
        name: "cebollas amarillas",
        quantity: "4",
        unit: "grandes en julianas finas",
      },
      { name: "mantequilla sin sal", quantity: "4", unit: "cucharadas" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "azúcar", quantity: "1", unit: "cucharadita (opcional)" },
      { name: "harina de trigo", quantity: "2", unit: "cucharadas" },
      { name: "vino blanco seco", quantity: "1/2", unit: "taza" },
      { name: "caldo de res", quantity: "1.5", unit: "litros" },
      { name: "tomillo seco", quantity: "1/2", unit: "cucharadita" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      {
        name: "pan (baguette o rústico)",
        quantity: "4",
        unit: "rebanadas gruesas tostadas",
      },
      { name: "queso Gruyère o Emmental rallado", quantity: "1", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla grande o cacerola, derretir la mantequilla con el aceite de oliva a fuego medio-bajo.",
      "Añadir las julianas de cebolla y el azúcar (si se usa). Cocinar lentamente, revolviendo ocasionalmente, por 30-40 minutos, o hasta que las cebollas estén caramelizadas y de color marrón dorado.",
      "Añadir la harina y cocinar, revolviendo, por 2 minutos.",
      "Verter el vino blanco y raspar el fondo de la olla para despegar cualquier trozo adherido. Dejar que el vino se evapore ligeramente.",
      "Incorporar el caldo de res, tomillo y la hoja de laurel. Llevar a ebullición.",
      "Reducir el fuego, tapar y cocinar a fuego lento por al menos 30 minutos.",
      "Retirar la hoja de laurel. Sazonar con sal y pimienta al gusto.",
      "Para servir: Verter la sopa en tazones individuales aptos para horno.",
      "Colocar una rebanada de pan tostado sobre cada tazón.",
      "Espolvorear generosamente con queso rallado.",
      "Gratinar en el horno o bajo el grill hasta que el queso esté derretido y burbujeante.",
      "Servir caliente.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pollo al Horno con Papas (Internacional, Estándar)",
    ingredients: [
      {
        name: "pollo entero o en piezas",
        quantity: "1",
        unit: "unidad o 1.5 kg de piezas",
      },
      { name: "papas", quantity: "500", unit: "gramos en cuartos" },
      { name: "cebolla", quantity: "1", unit: "mediana en cuartos" },
      { name: "zanahorias", quantity: "2", unit: "unidades en trozos grandes" },
      { name: "ajo", quantity: "4", unit: "dientes enteros" },
      { name: "aceite de oliva", quantity: "3", unit: "cucharadas" },
      { name: "pimentón dulce", quantity: "1", unit: "cucharada" },
      { name: "orégano seco", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "al gusto" },
      { name: "pimienta", quantity: "al gusto", unit: "al gusto" },
    ],
    instructions: [
      "Precalentar el horno a 200°C.",
      "Si se usa pollo entero, lavarlo y secarlo. Si se usan piezas, sazonarlas con sal y pimienta.",
      "En un bol grande, combinar las papas, cebolla, zanahorias y ajos.",
      "Rociar los vegetales con aceite de oliva, pimentón, orégano, sal y pimienta. Mezclar bien.",
      "Colocar el pollo (entero o piezas) en una bandeja para hornear grande.",
      "Distribuir los vegetales alrededor del pollo.",
      "Hornear por 45-60 minutos (para piezas) o 1.5 - 2 horas (para pollo entero), o hasta que el pollo esté cocido y los jugos salgan claros, y los vegetales estén tiernos y dorados.",
      "Servir caliente.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tortilla de Vegetales (Vegetariano, Bajo en Carbohidratos)",
    ingredients: [
      { name: "huevos", quantity: "4", unit: "unidades" },
      {
        name: "calabacín (zapallo)",
        quantity: "1/2",
        unit: "unidad en cubos pequeños",
      },
      {
        name: "pimiento rojo",
        quantity: "1/2",
        unit: "unidad en cubos pequeños",
      },
      { name: "cebolla", quantity: "1/4", unit: "unidad picada" },
      { name: "espinacas", quantity: "1", unit: "taza" },
      { name: "queso rallado (opcional)", quantity: "1/4", unit: "taza" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una sartén antiadherente, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla, pimiento rojo y calabacín hasta que estén tiernos.",
      "Añadir las espinacas y cocinar hasta que se marchiten.",
      "En un bol, batir los huevos con sal y pimienta.",
      "Verter los huevos batidos sobre los vegetales en la sartén.",
      "Si se usa queso, espolvorearlo por encima.",
      "Cocinar a fuego medio-bajo hasta que la tortilla esté cuajada por los bordes y casi en el centro.",
      "Opcionalmente, colocar bajo el grill del horno por 1-2 minutos para terminar de cuajar la parte superior.",
      "Deslizar la tortilla a un plato y cortar en porciones.",
      "Servir caliente o a temperatura ambiente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en carbohidratos",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pimientos Rellenos de Arroz y Carne (Cubana)",
    ingredients: [
      {
        name: "pimientos grandes (rojos, verdes o amarillos)",
        quantity: "4",
        unit: "unidades",
      },
      { name: "carne molida", quantity: "250", unit: "gramos" },
      { name: "arroz blanco cocido", quantity: "1", unit: "taza" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "salsa de tomate", quantity: "1/4", unit: "taza" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "orégano", quantity: "1/4", unit: "cucharadita" },
      { name: "aceitunas verdes picadas", quantity: "2", unit: "cucharadas" },
      { name: "aceite", quantity: "1", unit: "cucharada" },
      { name: "caldo de res o agua", quantity: "1/2", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Cortar la parte superior de los pimientos y retirar las semillas y membranas. Reservar las tapas.",
      "En una sartén, calentar el aceite a fuego medio.",
      "Sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir la carne molida y cocinar, desmenuzándola, hasta que esté dorada.",
      "Escurrir el exceso de grasa.",
      "Incorporar la salsa de tomate, comino, orégano, aceitunas, sal y pimienta. Cocinar por unos minutos.",
      "Retirar del fuego y mezclar con el arroz blanco cocido.",
      "Rellenar los pimientos con la mezcla de arroz y carne. Colocar las tapas encima.",
      "Colocar los pimientos rellenos en una olla o cazuela que puedan contenerlos de pie.",
      "Verter el caldo de res o agua en el fondo de la olla.",
      "Tapar y cocinar a fuego medio-bajo por 30-40 minutos, o hasta que los pimientos estén tiernos.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz con Camarones (Cubana)",
    ingredients: [
      { name: "arroz blanco", quantity: "1.5", unit: "tazas" },
      { name: "camarones limpios", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "mediana picada" },
      { name: "pimiento rojo", quantity: "1/2", unit: "unidad picado" },
      { name: "ajo", quantity: "3", unit: "dientes picados" },
      { name: "tomate triturado", quantity: "1/4", unit: "taza" },
      { name: "vino seco", quantity: "1/4", unit: "taza" },
      { name: "caldo de camarones o pescado", quantity: "3", unit: "tazas" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "pimentón dulce", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "perejil fresco picado", quantity: "para decorar", unit: "unidad" },
    ],
    instructions: [
      "Si no tienes caldo de camarones, puedes hacerlo hirviendo las cáscaras y cabezas de los camarones en agua con sal por unos minutos, luego colar.",
      "En una cazuela, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir el tomate triturado, comino y pimentón. Cocinar por 1 minuto.",
      "Incorporar el arroz crudo y remover por 1 minuto.",
      "Verter el vino seco y dejar que se evapore el alcohol.",
      "Añadir el caldo caliente. Sazonar con sal y pimienta al gusto.",
      "Llevar a ebullición, luego reducir el fuego al mínimo, tapar y cocinar por 15 minutos.",
      "Añadir los camarones y cocinar por 5-7 minutos más, o hasta que los camarones estén rosados y cocidos.",
      "Dejar reposar tapado por 5 minutos antes de servir.",
      "Servir caliente, decorado con perejil picado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Ensalada de Garbanzos con Atún (Alto en Proteínas, Sin Electricidad)",
    ingredients: [
      { name: "garbanzos cocidos", quantity: "400", unit: "gramos" },
      {
        name: "atún en lata (en agua o aceite)",
        quantity: "1",
        unit: "lata escurrida",
      },
      { name: "pimiento rojo", quantity: "1/4", unit: "unidad picado pequeño" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      {
        name: "maíz tierno (en lata)",
        quantity: "1/4",
        unit: "taza escurrido",
      },
      {
        name: "aceite de oliva virgen extra",
        quantity: "2",
        unit: "cucharadas",
      },
      { name: "vinagre o jugo de limón", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol grande, combinar los garbanzos cocidos, atún desmenuzado, pimiento rojo, cebolla roja y maíz.",
      "En un bol pequeño, mezclar el aceite de oliva, vinagre o jugo de limón, sal y pimienta para hacer el aderezo.",
      "Verter el aderezo sobre la ensalada.",
      "Mezclar suavemente para combinar.",
      "Servir frío.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Sopa de Puerro y Papa (Internacional, Vegetariano, Bajo en Calorías)",
    ingredients: [
      {
        name: "puerros (la parte blanca y verde claro)",
        quantity: "2",
        unit: "unidades en rodajas finas",
      },
      { name: "papas", quantity: "3", unit: "medianas en cubos" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "caldo de verduras", quantity: "1", unit: "litro" },
      {
        name: "mantequilla o aceite de oliva",
        quantity: "2",
        unit: "cucharadas",
      },
      { name: "crema de leche (opcional)", quantity: "1/4", unit: "taza" },
      { name: "perejil fresco picado (para decorar)", quantity: "al gusto", unit: "unidad" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Lavar bien los puerros para eliminar cualquier tierra.",
      "En una olla grande, derretir la mantequilla o calentar el aceite a fuego medio.",
      "Sofreír la cebolla y el puerro hasta que estén blandos (aproximadamente 5-7 minutos).",
      "Añadir el ajo y cocinar por 1 minuto más.",
      "Incorporar los cubos de papas y el caldo de verduras.",
      "Llevar a ebullición, luego reducir el fuego, tapar y cocinar a fuego lento por 15-20 minutos, o hasta que las papas estén muy tiernas.",
      "Retirar del fuego y triturar la sopa con una batidora de mano o en una licuadora hasta que esté suave. (Si no hay electricidad, machacar muy bien con un tenedor grande o pasapurés).",
      "Regresar la sopa a la olla (si se usó licuadora) y calentar suavemente.",
      "Si se usa, añadir la crema de leche y mezclar.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, decorada con perejil picado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Bistec Encebollado (Cubana)",
    ingredients: [
      {
        name: "bistec de res (nalga o palomilla)",
        quantity: "2",
        unit: "filetes finos",
      },
      { name: "cebolla", quantity: "1", unit: "grande en julianas" },
      { name: "ajo", quantity: "3", unit: "dientes machacados" },
      { name: "comino molido", quantity: "1", unit: "cucharadita" },
      { name: "orégano seco", quantity: "1/2", unit: "cucharadita" },
      { name: "vino seco o vinagre", quantity: "1/4", unit: "taza" },
      { name: "aceite vegetal", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Sazonar los bistecs con el ajo machacado, comino, orégano, sal y pimienta.",
      "En una sartén grande, calentar el aceite vegetal a fuego medio-alto.",
      "Dorar los bistecs por ambos lados (aproximadamente 2-3 minutos por lado para filetes finos). Retirar los bistecs y reservar.",
      "En la misma sartén, añadir las julianas de cebolla y cocinar a fuego medio, revolviendo ocasionalmente, hasta que estén blandas y ligeramente doradas.",
      "Verter el vino seco o vinagre y raspar el fondo de la sartén para despegar cualquier trozo adherido.",
      "Regresar los bistecs a la sartén con la cebolla. Cocinar por 1-2 minutos más para que los sabores se combinen.",
      "Servir caliente con la cebolla por encima.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Pechugas de Pollo Rellenas de Jamón y Queso (Cordon Bleu) (Internacional, Estándar)",
    ingredients: [
      {
        name: "pechugas de pollo sin piel ni hueso",
        quantity: "2",
        unit: "unidades grandes",
      },
      { name: "lonchas de jamón cocido", quantity: "4", unit: "unidades" },
      {
        name: "lonchas de queso suizo o Emmental",
        quantity: "4",
        unit: "unidades",
      },
      { name: "harina de trigo", quantity: "1/2", unit: "taza" },
      { name: "huevos", quantity: "2", unit: "unidades batidas" },
      { name: "pan rallado", quantity: "1", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "aceite para freír o para hornear", quantity: "suficiente", unit: "unidad" },
    ],
    instructions: [
      "Colocar cada pechuga de pollo entre dos trozos de papel film y aplanarla con un mazo o rodillo hasta que tenga un grosor uniforme (aproximadamente 1 cm).",
      "Sazonar las pechugas aplanadas con sal y pimienta.",
      "Colocar 2 lonchas de jamón y 2 lonchas de queso sobre la mitad de cada pechuga.",
      "Doblar la otra mitad de la pechuga sobre el relleno y sellar los bordes con palillos si es necesario.",
      "Pasar cada pechuga rellena por harina, luego por huevo batido y finalmente por pan rallado, cubriendo bien.",
      "Para freír: Calentar suficiente aceite en una sartén a fuego medio y freír las pechugas rellenas por 6-8 minutos por cada lado, o hasta que estén doradas y cocidas por dentro.",
      "Para hornear: Colocar las pechugas rellenas en una bandeja para hornear y hornear a 200°C por 20-25 minutos, o hasta que estén doradas y cocidas por dentro.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa Minestrone (Internacional, Vegetariano, Bajo en Grasas)",
    ingredients: [
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "cebolla", quantity: "1", unit: "mediana picada" },
      { name: "zanahorias", quantity: "2", unit: "unidades en cubos" },
      { name: "apio", quantity: "2", unit: "tallos en cubos" },
      { name: "ajo", quantity: "3", unit: "dientes picados" },
      { name: "calabacín (zapallo)", quantity: "1", unit: "unidad en cubos" },
      { name: "judías verdes", quantity: "1", unit: "taza cortadas" },
      { name: "tomate triturado", quantity: "400", unit: "gramos" },
      { name: "caldo de verduras", quantity: "1.5", unit: "litros" },
      { name: "agua", quantity: "1", unit: "taza" },
      {
        name: "pasta pequeña (ditalini, coditos)",
        quantity: "1/2",
        unit: "taza",
      },
      {
        name: "frijoles blancos (en lata)",
        quantity: "400",
        unit: "gramos escurridos y enjuagados",
      },
      { name: "espinacas frescas", quantity: "2", unit: "tazas" },
      { name: "orégano seco", quantity: "1", unit: "cucharadita" },
      { name: "albahaca seca", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      {
        name: "queso parmesano rallado (para servir, opcional)",
        quantity: "al gusto",
        unit: "unidad",
      },
    ],
    instructions: [
      "En una olla grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla, zanahorias y apio hasta que estén blandos (aproximadamente 5-7 minutos).",
      "Añadir el ajo y cocinar por 1 minuto más.",
      "Incorporar el calabacín, judías verdes, tomate triturado, caldo de verduras, agua, orégano y albahaca.",
      "Llevar a ebullición, luego reducir el fuego, tapar y cocinar a fuego lento por 15-20 minutos, o hasta que los vegetales estén tiernos.",
      "Añadir la pasta y los frijoles blancos. Cocinar por el tiempo indicado en el paquete de la pasta.",
      "Incorporar las espinacas y cocinar hasta que se marchiten.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, opcionalmente espolvoreada con queso parmesano rallado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz con Vegetales y Huevo Revuelto (Vegetariano, Bajo en Grasas)",
    ingredients: [
      { name: "arroz blanco cocido", quantity: "1.5", unit: "tazas" },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "cebolla", quantity: "1/4", unit: "unidad picada" },
      { name: "pimiento de colores", quantity: "1/2", unit: "unidad picado" },
      { name: "zanahoria", quantity: "1/2", unit: "unidad en cubos pequeños" },
      { name: "chícharos (guisantes)", quantity: "1/4", unit: "taza" },
      { name: "aceite vegetal", quantity: "1", unit: "cucharada" },
      { name: "salsa de soja (opcional)", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol, batir los huevos con sal y pimienta.",
      "En una sartén, calentar el aceite vegetal a fuego medio.",
      "Sofreír la cebolla, pimiento y zanahoria hasta que estén tiernos.",
      "Añadir los chícharos y cocinar por 1 minuto más.",
      "Incorporar el arroz cocido y mezclar con los vegetales.",
      "Hacer un hueco en el centro de la sartén y verter los huevos batidos.",
      "Cocinar los huevos revueltos, mezclándolos con el arroz y los vegetales a medida que se cocinan.",
      "Si se usa, añadir la salsa de soja y mezclar bien.",
      "Servir caliente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Ensalada de Atún con Maíz y Frijoles (Sin Electricidad, Alto en Proteínas)",
    ingredients: [
      {
        name: "atún en lata (en agua o aceite)",
        quantity: "1",
        unit: "lata escurrida",
      },
      {
        name: "maíz tierno (en lata)",
        quantity: "1/2",
        unit: "taza escurrido",
      },
      {
        name: "frijoles negros (en lata)",
        quantity: "1/2",
        unit: "taza escurridos y enjuagados",
      },
      {
        name: "pimiento verde",
        quantity: "1/4",
        unit: "unidad picado pequeño",
      },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      { name: "cilantro fresco picado", quantity: "1", unit: "cucharada" },
      {
        name: "aceite de oliva virgen extra",
        quantity: "2",
        unit: "cucharadas",
      },
      { name: "jugo de limón", quantity: "1", unit: "cucharada" },
      { name: "comino molido", quantity: "1/4", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol grande, combinar el atún desmenuzado, maíz, frijoles negros, pimiento verde, cebolla roja y cilantro.",
      "En un bol pequeño, mezclar el aceite de oliva, jugo de limón, comino, sal y pimienta para hacer el aderezo.",
      "Verter el aderezo sobre la ensalada.",
      "Mezclar suavemente para combinar.",
      "Servir frío.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Pollo con Fideos (Internacional, Bajo en Grasas)",
    ingredients: [
      { name: "pechuga de pollo", quantity: "1", unit: "unidad" },
      {
        name: "fideos (tipo cabello de ángel o finos)",
        quantity: "50",
        unit: "gramos",
      },
      { name: "zanahoria", quantity: "1", unit: "unidad en rodajas finas" },
      { name: "apio", quantity: "1", unit: "tallo en rodajas finas" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "caldo de pollo", quantity: "1.5", unit: "litros" },
      { name: "perejil fresco", quantity: "1", unit: "cucharada picado" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una olla grande, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir la pechuga de pollo entera, zanahoria y apio.",
      "Verter el caldo de pollo. Llevar a ebullición.",
      "Reducir el fuego, tapar y cocinar a fuego lento por 20 minutos.",
      "Retirar la pechuga de pollo, desmenuzarla y regresarla a la sopa.",
      "Añadir los fideos y cocinar según las instrucciones del paquete.",
      "Añadir el perejil picado.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Pescado al Vapor con Vegetales (Bajo en Calorías, Alto en Proteínas)",
    ingredients: [
      { name: "filetes de pescado blanco", quantity: "2", unit: "unidades" },
      { name: "brócoli", quantity: "1", unit: "taza en floretes" },
      { name: "zanahorias", quantity: "1", unit: "unidad en rodajas finas" },
      { name: "pimiento rojo", quantity: "1/2", unit: "unidad en tiras" },
      { name: "jugo de limón", quantity: "1", unit: "cucharada" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "agua", quantity: "para cocinar al vapor", unit: "unidad" },
    ],
    instructions: [
      "Llenar una olla con unos centímetros de agua y colocar una cesta para cocinar al vapor dentro.",
      "Llevar el agua a ebullición.",
      "Sazonar los filetes de pescado con sal y pimienta.",
      "Colocar los vegetales en la cesta de vapor.",
      "Colocar los filetes de pescado sobre los vegetales.",
      "Rociar el pescado con jugo de limón y aceite de oliva.",
      "Tapar la olla y cocinar al vapor por 8-12 minutos, o hasta que el pescado esté cocido y los vegetales tiernos pero crujientes.",
      "Servir caliente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tortilla de Camarones (Cubana)",
    ingredients: [
      { name: "camarones pequeños cocidos", quantity: "200", unit: "gramos" },
      { name: "huevos", quantity: "4", unit: "unidades" },
      { name: "cebolla", quantity: "1/4", unit: "unidad picada finamente" },
      {
        name: "pimiento verde",
        quantity: "1/4",
        unit: "unidad picado finamente",
      },
      { name: "ajo", quantity: "1", unit: "diente picado" },
      { name: "aceite", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una sartén, calentar el aceite a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir los camarones cocidos y cocinar por 1-2 minutos para que se calienten.",
      "En un bol, batir los huevos con sal y pimienta.",
      "Verter los huevos batidos sobre los camarones y vegetales en la sartén.",
      "Cocinar a fuego medio-bajo hasta que la tortilla esté cuajada por un lado.",
      "Dar la vuelta a la tortilla con cuidado y cocinar el otro lado hasta que esté cocida.",
      "Servir caliente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arroz con Frijoles Colorados (Cubana)",
    ingredients: [
      { name: "arroz blanco", quantity: "2", unit: "tazas" },
      { name: "frijoles colorados (rojos)", quantity: "1", unit: "taza" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento verde", quantity: "1", unit: "mediano" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "orégano", quantity: "1/2", unit: "cucharadita" },
      { name: "laurel", quantity: "1", unit: "hoja" },
      { name: "aceite", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Remojar los frijoles colorados en agua durante la noche.",
      "Escurrir y cocinar los frijoles en agua con la hoja de laurel hasta que estén tiernos.",
      "En una olla grande, calentar el aceite y sofreír la cebolla, el pimiento y el ajo picados.",
      "Añadir el comino y orégano. Cocinar por 1 minuto.",
      "Agregar el arroz y mezclar para que se impregne del sofrito.",
      "Añadir los frijoles con parte de su caldo de cocción (aproximadamente 3-4 tazas de líquido en total).",
      "Ajustar la sal y pimienta. Llevar a ebullición.",
      "Reducir el fuego al mínimo, tapar y cocinar por 15-20 minutos, o hasta que el arroz esté tierno y el líquido se haya absorbido.",
      "Dejar reposar tapado por 5 minutos antes de servir.",
    ],
    prepTime: "> 60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Pollo y Aguacate (Alto en Proteínas)",
    ingredients: [
      {
        name: "pechuga de pollo cocida y desmenuzada",
        quantity: "1",
        unit: "unidad",
      },
      { name: "aguacate maduro", quantity: "1", unit: "unidad en cubos" },
      { name: "tomate", quantity: "1", unit: "unidad en cubos" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad picada finamente",
      },
      { name: "cilantro fresco picado", quantity: "2", unit: "cucharadas" },
      { name: "jugo de limón", quantity: "1", unit: "cucharada" },
      {
        name: "aceite de oliva virgen extra",
        quantity: "1",
        unit: "cucharada",
      },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En un bol grande, combinar el pollo cocido y desmenuzado, aguacate en cubos, tomate en cubos, cebolla roja picada y cilantro.",
      "Rociar con jugo de limón y aceite de oliva.",
      "Sazonar con sal y pimienta al gusto.",
      "Mezclar suavemente para combinar.",
      "Servir inmediatamente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sopa de Maíz y Pollo (Cubana)",
    ingredients: [
      { name: "maíz tierno (granos)", quantity: "2", unit: "tazas" },
      { name: "pollo cocido y desmenuzado", quantity: "1", unit: "taza" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "pimiento verde", quantity: "1/4", unit: "unidad picado" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "caldo de pollo", quantity: "1", unit: "litro" },
      { name: "leche (opcional)", quantity: "1/2", unit: "taza" },
      { name: "mantequilla o aceite", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      {
        name: "cilantro fresco picado (para decorar)",
        quantity: "al gusto",
        unit: "unidad",
      },
    ],
    instructions: [
      "En una olla, derretir la mantequilla o calentar el aceite a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir los granos de maíz y cocinar por unos minutos.",
      "Verter el caldo de pollo y la leche (si se usa). Llevar a ebullición suave.",
      "Reducir el fuego y cocinar a fuego lento por 10-15 minutos.",
      "Añadir el pollo cocido y desmenuzado y calentar por unos minutos.",
      "Opcionalmente, triturar una parte de la sopa con una batidora de mano para espesarla.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, decorada con cilantro picado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Frijoles Negros Fritos (Cubana, Vegetariano, Bajo en Grasas)",
    ingredients: [
      {
        name: "frijoles negros cocidos (con poco caldo)",
        quantity: "2",
        unit: "tazas",
      },
      { name: "cebolla", quantity: "1/4", unit: "unidad picada finamente" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "comino molido", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una sartén, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir los frijoles negros cocidos (con un poco de su caldo) y el comino.",
      "Cocinar, machacando los frijoles con una cuchara de madera o tenedor, hasta que se forme una pasta espesa y se doren ligeramente.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, tradicionalmente con arroz blanco.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pescado en Salsa Roja (Cubana)",
    ingredients: [
      { name: "filetes de pescado blanco", quantity: "2", unit: "unidades" },
      { name: "tomate triturado", quantity: "1", unit: "taza" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "pimiento rojo", quantity: "1/4", unit: "unidad picado" },
      { name: "ajo", quantity: "3", unit: "dientes picados" },
      { name: "vino seco o vinagre", quantity: "1/4", unit: "taza" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "orégano", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Sazonar los filetes de pescado con sal y pimienta.",
      "En una sartén, calentar el aceite de oliva a fuego medio.",
      "Sofreír la cebolla, pimiento y ajo hasta que estén transparentes.",
      "Añadir el tomate triturado, vino seco o vinagre, comino y orégano.",
      "Llevar a ebullición suave y cocinar la salsa por unos 5-7 minutos.",
      "Colocar los filetes de pescado en la salsa, asegurándose de que estén cubiertos.",
      "Reducir el fuego, tapar y cocinar a fuego lento por 8-10 minutos, o hasta que el pescado esté cocido.",
      "Servir caliente con la salsa por encima.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Arroz con Vegetales al Curry (Internacional, Vegetariano, Bajo en Grasas)",
    ingredients: [
      { name: "arroz basmati", quantity: "1", unit: "taza" },
      { name: "agua o caldo de verduras", quantity: "1.5", unit: "tazas" },
      { name: "aceite vegetal", quantity: "1", unit: "cucharada" },
      { name: "cebolla", quantity: "1/2", unit: "unidad picada" },
      { name: "ajo", quantity: "2", unit: "dientes picados" },
      { name: "jengibre fresco", quantity: "1/2", unit: "cucharadita rallado" },
      {
        name: "pasta de curry amarillo o rojo",
        quantity: "1",
        unit: "cucharada",
      },
      { name: "leche de coco ligera", quantity: "200", unit: "ml" },
      {
        name: "vegetales mixtos (brócoli, zanahoria, pimiento)",
        quantity: "2",
        unit: "tazas en trozos",
      },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      {
        name: "cilantro fresco picado (para decorar)",
        quantity: "al gusto",
        unit: "unidad",
      },
    ],
    instructions: [
      "Cocer el arroz basmati según las instrucciones del paquete.",
      "Mientras el arroz se cuece, calentar el aceite vegetal en una sartén grande o wok a fuego medio.",
      "Sofreír la cebolla, ajo y jengibre hasta que estén fragantes (1-2 minutos).",
      "Añadir la pasta de curry y cocinar, revolviendo, por 1 minuto.",
      "Incorporar los vegetales mixtos y cocinar por 5-7 minutos, o hasta que estén tiernos pero crujientes.",
      "Verter la leche de coco y llevar a ebullición suave.",
      "Reducir el fuego y cocinar a fuego lento por 5 minutos más.",
      "Sazonar con sal al gusto.",
      "Servir el curry de vegetales sobre el arroz cocido, decorado con cilantro picado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en grasas",
    createdAt: new Date().toISOString(),
  },
];
