import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de cenas cubanas e internacionales
 */
export const CENAS: Recipe[] = [
  {
    id: generateId(),
    title: "Tortilla de Papas Cubana",
    ingredients: [
      { name: "papas", quantity: "3", unit: "medianas" },
      { name: "huevos", quantity: "4", unit: "unidades" },
      { name: "cebolla", quantity: "1", unit: "pequeña" },
      { name: "aceite", quantity: "4", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Pelar y cortar las papas en rodajas finas",
      "Picar la cebolla en trozos pequeños",
      "Calentar el aceite en una sartén y freír las papas a fuego medio-bajo",
      "Añadir la cebolla y seguir cocinando hasta que las papas estén tiernas",
      "Batir los huevos en un recipiente aparte, añadir sal",
      "Escurrir el exceso de aceite de las papas y añadirlas a los huevos",
      "Mezclar bien y verter todo de nuevo en la sartén",
      "Cocinar a fuego medio-bajo hasta que la base esté cuajada",
      "Dar la vuelta a la tortilla con ayuda de un plato y cocinar el otro lado",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Vegetales con Limón (Sin Electricidad)",
    ingredients: [
      { name: "lechuga", quantity: "1", unit: "pequeña" },
      { name: "tomate", quantity: "2", unit: "unidades" },
      { name: "pepino", quantity: "1", unit: "unidad" },
      { name: "zanahoria", quantity: "1", unit: "unidad" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Lavar y trocear la lechuga en trozos pequeños",
      "Cortar los tomates y el pepino en cubos",
      "Rallar la zanahoria",
      "Mezclar todos los vegetales en un recipiente grande",
      "Aliñar con jugo de limón, aceite y sal al gusto",
      "Mezclar bien antes de servir",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pollo a la Plancha con Limón",
    ingredients: [
      { name: "pechugas de pollo", quantity: "2", unit: "unidades" },
      { name: "limón", quantity: "1", unit: "unidad" },
      { name: "ajo", quantity: "2", unit: "dientes" },
      { name: "orégano", quantity: "1", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "pimienta", quantity: "1/2", unit: "cucharadita" },
    ],
    instructions: [
      "Aplanar ligeramente las pechugas de pollo para que tengan un grosor uniforme",
      "Mezclar el jugo de limón, ajo picado, orégano, sal y pimienta en un recipiente",
      "Marinar el pollo en esta mezcla por al menos 15 minutos",
      "Calentar una plancha o sartén con aceite de oliva",
      "Cocinar el pollo a fuego medio-alto, aproximadamente 5-6 minutos por cada lado",
      "Verificar que esté bien cocido y servir caliente con rodajas de limón",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Cena",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Picadillo Cubano",
    ingredients: [
      { name: "carne molida", quantity: "500", unit: "gramos" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "pimiento", quantity: "1", unit: "mediano" },
      { name: "ajo", quantity: "3", unit: "dientes" },
      { name: "salsa de tomate", quantity: "1/4", unit: "taza" },
      { name: "aceitunas verdes", quantity: "1/4", unit: "taza" },
      { name: "pasas", quantity: "1/4", unit: "taza" },
      { name: "comino", quantity: "1/2", unit: "cucharadita" },
      { name: "orégano", quantity: "1/2", unit: "cucharadita" },
      { name: "aceite", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "pimienta", quantity: "1/4", unit: "cucharadita" },
    ],
    instructions: [
      "Picar finamente la cebolla, el pimiento y el ajo",
      "Calentar el aceite en una sartén grande y sofreír la cebolla y el pimiento",
      "Añadir el ajo y cocinar por 1 minuto más",
      "Agregar la carne molida y cocinar hasta que pierda el color rosado",
      "Añadir el comino, orégano, sal y pimienta",
      "Incorporar la salsa de tomate y mezclar bien",
      "Añadir las aceitunas picadas y las pasas",
      "Cocinar a fuego medio-bajo por 15-20 minutos hasta que los sabores se integren",
      "Servir caliente con arroz blanco",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Espaguetis con Salsa de Tomate Casera",
    ingredients: [
      { name: "espaguetis", quantity: "250", unit: "gramos" },
      { name: "tomates", quantity: "4", unit: "unidades" },
      { name: "cebolla", quantity: "1", unit: "mediana" },
      { name: "ajo", quantity: "2", unit: "dientes" },
      { name: "albahaca", quantity: "8", unit: "hojas" },
      { name: "aceite de oliva", quantity: "3", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Hervir agua con sal en una olla grande",
      "Cocer los espaguetis según las instrucciones del paquete",
      "Mientras tanto, pelar y picar la cebolla y el ajo",
      "Cortar los tomates en cubos",
      "En una sartén grande, calentar el aceite y sofreír la cebolla y el ajo",
      "Añadir los tomates y cocinar a fuego medio hasta que se forme una salsa",
      "Triturar ligeramente con un tenedor para obtener una textura semi-espesa",
      "Añadir la albahaca picada al final",
      "Mezclar los espaguetis con la salsa y servir caliente",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tortilla de Papa y Cebolla (Sin Electricidad)",
    ingredients: [
      { name: "papas", quantity: "2", unit: "medianas" },
      { name: "cebolla", quantity: "1", unit: "pequeña" },
      { name: "huevos", quantity: "4", unit: "unidades" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Pelar y cortar las papas en rodajas finas",
      "Picar la cebolla en juliana",
      "Calentar el aceite en una sartén y freír las papas y la cebolla a fuego medio-bajo",
      "Batir los huevos en un recipiente y añadir sal",
      "Cuando las papas estén blandas, escurrir el exceso de aceite",
      "Mezclar las papas y cebolla con los huevos batidos",
      "Verter la mezcla en la sartén y cocinar a fuego medio-bajo",
      "Cuando la base esté cuajada, dar la vuelta con ayuda de un plato",
      "Cocinar el otro lado y servir caliente o a temperatura ambiente",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Cena",
    dietType: "Bajo en carbohidratos",
    createdAt: new Date().toISOString(),
  },
];
