import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de desayunos cubanos e internacionales
 */
export const DESAYUNOS: Recipe[] = [
  // Recetas existentes (manteniendo las originales)
  {
    id: generateId(),
    title: "Tostada de Pan con Aguacate",
    ingredients: [
      { name: "pan integral", quantity: "2", unit: "rebanadas" },
      { name: "aguacate", quantity: "1", unit: "unidad" },
      { name: "sal", quantity: "1", unit: "pizca" },
      { name: "limón", quantity: "1/2", unit: "unidad" },
    ],
    instructions: [
      "Tostar el pan hasta que esté crujiente",
      "Cortar el aguacate por la mitad, quitar el hueso y extraer la pulpa",
      "Machacar el aguacate en un recipiente con un tenedor",
      "Añadir sal y jugo de limón al gusto",
      "Untar el aguacate sobre el pan tostado",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Revoltillo de Huevo con Tomate",
    ingredients: [
      { name: "huevos", quantity: "3", unit: "unidades" },
      { name: "tomate", quantity: "1", unit: "mediano" },
      { name: "cebolla", quantity: "1/2", unit: "pequeña" },
      { name: "aceite", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Picar la cebolla y el tomate en cuadritos pequeños",
      "Batir los huevos en un recipiente y añadir sal al gusto",
      "Calentar el aceite en una sartén a fuego medio",
      "Añadir la cebolla y cocinar hasta que esté transparente",
      "Agregar el tomate y cocinar por 2 minutos más",
      "Verter los huevos batidos y revolver constantemente hasta que estén cocinados pero jugosos",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Avena Remojada con Frutas (Sin Electricidad)",
    ingredients: [
      { name: "avena", quantity: "1/2", unit: "taza" },
      { name: "leche o agua", quantity: "1", unit: "taza" },
      { name: "plátano", quantity: "1", unit: "unidad" },
      { name: "miel", quantity: "1", unit: "cucharada" },
      { name: "canela", quantity: "1/4", unit: "cucharadita" },
    ],
    instructions: [
      "Mezclar la avena con la leche o agua en un recipiente",
      "Añadir miel y canela al gusto",
      "Tapar y dejar reposar durante toda la noche",
      "A la mañana siguiente, cortar el plátano en rodajas",
      "Mezclar con la avena remojada y servir frío",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tostadas Francesas Cubanas",
    ingredients: [
      { name: "pan", quantity: "4", unit: "rebanadas" },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "leche", quantity: "1/4", unit: "taza" },
      { name: "azúcar", quantity: "2", unit: "cucharadas" },
      { name: "canela", quantity: "1/2", unit: "cucharadita" },
      { name: "vainilla", quantity: "1/2", unit: "cucharadita" },
      { name: "mantequilla", quantity: "1", unit: "cucharada" },
    ],
    instructions: [
      "Batir los huevos, leche, azúcar, canela y vainilla en un recipiente hondo",
      "Sumergir cada rebanada de pan en la mezcla, asegurándote que se empape bien",
      "Calentar la mantequilla en una sartén a fuego medio",
      "Cocinar cada rebanada por ambos lados hasta que esté dorada",
      "Servir caliente, opcionalmente con miel o sirope por encima",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Batido de Frutas Tropical (Sin Electricidad)",
    ingredients: [
      { name: "plátano maduro", quantity: "1", unit: "unidad" },
      { name: "mango", quantity: "1", unit: "unidad" },
      { name: "naranja", quantity: "1", unit: "unidad" },
      { name: "agua", quantity: "1/2", unit: "taza" },
      { name: "azúcar", quantity: "1", unit: "cucharada" },
    ],
    instructions: [
      "Pelar y cortar el plátano y el mango en trozos pequeños",
      "Exprimir la naranja y reservar el jugo",
      "En un frasco con tapa, añadir todas las frutas picadas",
      "Agregar el jugo de naranja, agua y azúcar",
      "Cerrar bien el frasco y agitar vigorosamente durante 2-3 minutos",
      "Servir inmediatamente con hielo opcional",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Desayuno Proteico de Frijoles Negros",
    ingredients: [
      { name: "frijoles negros cocidos", quantity: "1", unit: "taza" },
      { name: "huevo", quantity: "1", unit: "unidad" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "ajo", quantity: "1", unit: "diente" },
      { name: "comino", quantity: "1/4", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Picar finamente la cebolla y el ajo",
      "Calentar el aceite en una sartén y sofreír la cebolla y el ajo",
      "Añadir los frijoles negros cocidos y el comino",
      "Machacar ligeramente los frijoles mientras se calientan",
      "Hacer un hueco en el centro y romper el huevo en él",
      "Cocinar hasta que el huevo esté al punto deseado",
      "Servir caliente",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pan con Lechón Desmenuzado",
    ingredients: [
      { name: "pan cubano o baguette", quantity: "1", unit: "unidad" },
      { name: "lechón asado desmenuzado", quantity: "1", unit: "taza" },
      { name: "mojo criollo", quantity: "2", unit: "cucharadas" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "lechuga", quantity: "2", unit: "hojas" },
    ],
    instructions: [
      "Cortar el pan por la mitad a lo largo",
      "Calentar el lechón desmenuzado con un poco de mojo criollo",
      "Picar la cebolla en rodajas finas",
      "Lavar y secar las hojas de lechuga",
      "Montar el sándwich colocando el lechón, la cebolla y la lechuga",
      "Presionar ligeramente y cortar en porciones",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(), // Usar generateId() para nuevos elementos
    title: "Tostadas de aguacate y huevo",
    ingredients: [
      { name: "Pan", quantity: "2", unit: "rebanadas" },
      { name: "Aguacate", quantity: "1", unit: "unidad" },
      { name: "Huevos", quantity: "2", unit: "unidades" },
      { name: "Tomate cherry", quantity: "5", unit: "unidades" },
      { name: "Aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "Sal", quantity: "1", unit: "pizca" },
      { name: "Pimienta", quantity: "1", unit: "pizca" },
      { name: "Zumo de limón", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Tostar el pan hasta que esté dorado y crujiente.",
      "Cortar el aguacate por la mitad, quitar el hueso y machacar la pulpa en un bol.",
      "Añadir el zumo de limón, sal y pimienta al aguacate y mezclar bien.",
      "Extender la mezcla de aguacate sobre las tostadas.",
      "En una sartén con aceite de oliva, freír los huevos al gusto (estrellados o revueltos).",
      "Colocar los huevos sobre las tostadas de aguacate.",
      "Cortar los tomates cherry por la mitad y colocarlos alrededor del plato.",
      "Servir inmediatamente mientras está caliente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Huevos Rancheros (Internacional)",
    ingredients: [
      { name: "tortillas de maíz", quantity: "2", unit: "unidades" },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "salsa ranchera", quantity: "1/2", unit: "taza" },
      { name: "queso rallado", quantity: "1/4", unit: "taza" },
      { name: "aceite", quantity: "1", unit: "cucharada" },
      { name: "cilantro fresco", quantity: "1", unit: "cucharada" },
    ],
    instructions: [
      "Calentar el aceite en una sartén y freír ligeramente las tortillas hasta que estén suaves.",
      "Retirar las tortillas y colocar en un plato.",
      "En la misma sartén, freír los huevos al gusto (estrellados son tradicionales).",
      "Calentar la salsa ranchera en una olla pequeña.",
      "Colocar los huevos sobre las tortillas.",
      "Cubrir con la salsa ranchera caliente.",
      "Espolvorear con queso rallado y cilantro picado.",
      "Servir inmediatamente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Panqueques Americanos (Internacional)",
    ingredients: [
      { name: "harina de trigo", quantity: "1", unit: "taza" },
      { name: "levadura en polvo", quantity: "2", unit: "cucharaditas" },
      { name: "azúcar", quantity: "2", unit: "cucharadas" },
      { name: "sal", quantity: "1/2", unit: "cucharadita" },
      { name: "huevo", quantity: "1", unit: "unidad" },
      { name: "leche", quantity: "1", unit: "taza" },
      { name: "mantequilla derretida", quantity: "2", unit: "cucharadas" },
    ],
    instructions: [
      "En un bol grande, mezclar la harina, levadura, azúcar y sal.",
      "En otro bol, batir el huevo, la leche y la mantequilla derretida.",
      "Verter los ingredientes líquidos sobre los secos y mezclar hasta combinar (no batir en exceso, los grumos están bien).",
      "Calentar una sartén antiadherente o plancha a fuego medio y engrasar ligeramente.",
      "Verter 1/4 taza de masa por cada panqueque.",
      "Cocinar hasta que aparezcan burbujas en la superficie y los bordes se vean cocidos (aproximadamente 2-3 minutos).",
      "Dar la vuelta y cocinar el otro lado hasta que esté dorado.",
      "Servir caliente con sirope de arce, mantequilla o frutas.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Gachas de Avena con Bayas (Internacional, Bajo en Calorías)",
    ingredients: [
      { name: "avena en hojuelas", quantity: "1/2", unit: "taza" },
      { name: "agua o leche", quantity: "1", unit: "taza" },
      { name: "bayas mixtas", quantity: "1/2", unit: "taza" },
      {
        name: "miel o sirope de arce",
        quantity: "1",
        unit: "cucharadita (opcional)",
      },
    ],
    instructions: [
      "En una olla pequeña, combinar la avena y el líquido.",
      "Llevar a ebullición, luego reducir el fuego y cocinar a fuego lento por 5-7 minutos, revolviendo ocasionalmente, hasta que espese.",
      "Verter en un bol y añadir las bayas por encima.",
      "Endulzar con miel o sirope si se desea.",
      "Servir caliente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Yogur con Granola y Frutas (Sin Electricidad, Alto en Proteínas)",
    ingredients: [
      { name: "yogur griego natural", quantity: "1", unit: "taza" },
      { name: "granola", quantity: "1/4", unit: "taza" },
      {
        name: "frutas frescas (ej: fresas, arándanos)",
        quantity: "1/2",
        unit: "taza",
      },
      {
        name: "semillas de chía",
        quantity: "1",
        unit: "cucharadita (opcional)",
      },
    ],
    instructions: [
      "En un bol o vaso, colocar el yogur griego.",
      "Espolvorear la granola por encima.",
      "Añadir las frutas frescas cortadas.",
      "Opcionalmente, añadir semillas de chía.",
      "Servir inmediatamente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tortilla Española (Internacional, Intermedia)",
    ingredients: [
      { name: "papas", quantity: "4", unit: "medianas" },
      { name: "cebolla", quantity: "1", unit: "grande" },
      { name: "huevos", quantity: "6", unit: "unidades" },
      { name: "aceite de oliva virgen extra", quantity: "1", unit: "taza" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Pelar las papas y cortarlas en rodajas finas.",
      "Pelar y picar la cebolla en juliana fina.",
      "Calentar el aceite de oliva en una sartén grande a fuego medio-bajo.",
      "Añadir las papas y la cebolla a la sartén. Cocinar lentamente, removiendo ocasionalmente, hasta que estén tiernas y ligeramente doradas (no fritas crujientes). Esto puede tardar 20-30 minutos.",
      "Escurrir el exceso de aceite de las papas y la cebolla y colocarlas en un bol.",
      "En el bol con las papas y cebolla, añadir los huevos batidos y sal al gusto. Mezclar bien.",
      "En la misma sartén (con un poco del aceite restante o un chorrito nuevo si es necesario), verter la mezcla.",
      "Cocinar a fuego medio-bajo. Cuando los bordes empiecen a cuajar, despegar con una espátula.",
      "Para dar la vuelta, colocar un plato grande sobre la sartén y, con cuidado, invertir la tortilla sobre el plato.",
      "Deslizar la tortilla de nuevo a la sartén para cocinar el otro lado hasta que esté cuajada por dentro pero jugosa.",
      "Servir caliente o a temperatura ambiente.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Smoothie Verde Energizante (Sin Electricidad, Bajo en Calorías)",
    ingredients: [
      { name: "espinacas frescas", quantity: "1", unit: "taza" },
      { name: "plátano maduro", quantity: "1/2", unit: "unidad" },
      { name: "manzana", quantity: "1/2", unit: "unidad" },
      { name: "agua de coco o agua", quantity: "1", unit: "taza" },
      {
        name: "semillas de lino o chía",
        quantity: "1",
        unit: "cucharadita (opcional)",
      },
    ],
    instructions: [
      "Picar la espinaca, plátano y manzana en trozos pequeños.",
      "Colocar todos los ingredientes en un frasco o recipiente con tapa.",
      "Cerrar bien y agitar vigorosamente por 2-3 minutos hasta que las frutas y espinacas se desintegren lo más posible.",
      "Servir inmediatamente. (Nota: La textura no será tan suave como con una batidora).",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Arepas con Queso (Internacional, Fácil)",
    ingredients: [
      {
        name: "harina de maíz precocida (Harina P.A.N.)",
        quantity: "1",
        unit: "taza",
      },
      { name: "agua tibia", quantity: "1.5", unit: "tazas" },
      { name: "sal", quantity: "1/2", unit: "cucharadita" },
      {
        name: "queso rallado (mozzarella o telita)",
        quantity: "1/2",
        unit: "taza",
      },
      { name: "aceite", quantity: "para cocinar", unit: "unidad" },
    ],
    instructions: [
      "En un bol, mezclar la harina de maíz y la sal.",
      "Añadir el agua tibia gradualmente mientras se mezcla con las manos hasta obtener una masa suave y homogénea que no se pegue.",
      "Dejar reposar la masa por 5 minutos.",
      "Dividir la masa en porciones y formar bolas. Luego, aplastar cada bola para formar discos de aproximadamente 1 cm de grosor.",
      "Hacer un hueco en el centro de cada arepa y rellenar con queso rallado.",
      "Cerrar la arepa, asegurándose de que el queso quede dentro.",
      "Calentar un poco de aceite en una sartén o plancha a fuego medio.",
      "Cocinar las arepas por ambos lados hasta que estén doradas y cocidas por dentro (aproximadamente 7-10 minutos por lado).",
      "Servir calientes.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  // --- 10 Recetas adicionales para Desayuno ---
  {
    id: generateId(),
    title:
      "Café con Leche y Tostada con Mantequilla (Cubana, Sin Electricidad)",
    ingredients: [
      { name: "café fuerte", quantity: "1/4", unit: "taza" },
      { name: "leche caliente", quantity: "3/4", unit: "taza" },
      { name: "azúcar", quantity: "al gusto", unit: "unidad" },
      { name: "pan cubano o baguette", quantity: "1", unit: "rebanada" },
      { name: "mantequilla", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Preparar café fuerte.",
      "Calentar la leche.",
      "Mezclar el café caliente con la leche caliente en una taza.",
      "Añadir azúcar al gusto y revolver.",
      "Tostar el pan (si es posible, si no, usar pan fresco).",
      "Untar mantequilla en la tostada.",
      "Servir el café con leche caliente con la tostada.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Frutas Frescas con Miel y Limón (Sin Electricidad, Bajo en Calorías)",
    ingredients: [
      {
        name: "variedad de frutas frescas (papaya, mango, piña)",
        quantity: "2",
        unit: "tazas picadas",
      },
      { name: "miel", quantity: "1", unit: "cucharada" },
      { name: "jugo de limón", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Lavar, pelar y picar las frutas en trozos pequeños.",
      "Colocar las frutas picadas en un bol.",
      "Rociar con miel y jugo de limón.",
      "Mezclar suavemente.",
      "Servir inmediatamente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title:
      "Tortilla de Claras con Vegetales (Alto en Proteínas, Bajo en Carbohidratos)",
    ingredients: [
      { name: "claras de huevo", quantity: "3", unit: "unidades" },
      { name: "pimiento rojo", quantity: "1/4", unit: "unidad picado" },
      { name: "cebolla", quantity: "1/4", unit: "unidad picada" },
      { name: "espinacas", quantity: "1/2", unit: "taza" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharadita" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una sartén pequeña, calentar el aceite de oliva a fuego medio.",
      "Sofreír el pimiento y la cebolla picados hasta que estén tiernos.",
      "Añadir las espinacas y cocinar hasta que se marchiten.",
      "En un bol, batir las claras de huevo con sal y pimienta.",
      "Verter las claras batidas sobre los vegetales en la sartén.",
      "Cocinar hasta que la tortilla esté cuajada por un lado.",
      "Doblar la tortilla por la mitad y cocinar por un minuto más.",
      "Servir caliente.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pan con Mantequilla y Azúcar (Cubana, Sin Electricidad)",
    ingredients: [
      { name: "pan cubano o baguette", quantity: "1", unit: "rebanada" },
      { name: "mantequilla", quantity: "al gusto", unit: "unidad" },
      { name: "azúcar", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Cortar una rebanada de pan.",
      "Untar mantequilla generosamente sobre el pan.",
      "Espolvorear azúcar sobre la mantequilla.",
      "Servir.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Muesli con Leche y Frutos Secos (Internacional, Sin Electricidad)",
    ingredients: [
      { name: "muesli", quantity: "1/2", unit: "taza" },
      { name: "leche (animal o vegetal)", quantity: "1", unit: "taza" },
      {
        name: "frutos secos (nueces, almendras)",
        quantity: "1/4",
        unit: "taza",
      },
      { name: "fruta fresca picada (opcional)", quantity: "1/4", unit: "taza" },
    ],
    instructions: [
      "En un bol, combinar el muesli y la leche.",
      "Añadir los frutos secos y la fruta fresca picada (si se usa).",
      "Mezclar bien.",
      "Dejar reposar por unos minutos para que el muesli se ablande ligeramente.",
      "Servir.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Torrejas Cubanas (Tostadas Francesas)",
    ingredients: [
      {
        name: "pan del día anterior",
        quantity: "4",
        unit: "rebanadas gruesas",
      },
      { name: "leche", quantity: "1", unit: "taza" },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "azúcar", quantity: "1/4", unit: "taza" },
      { name: "canela en polvo", quantity: "1", unit: "cucharadita" },
      { name: "vainilla", quantity: "1/2", unit: "cucharadita" },
      { name: "mantequilla o aceite", quantity: "para freír", unit: "unidad" },
    ],
    instructions: [
      "En un bol hondo, batir los huevos con la leche, azúcar, canela y vainilla.",
      "Sumergir cada rebanada de pan en la mezcla, asegurándose de que se empape bien por ambos lados.",
      "Calentar mantequilla o aceite en una sartén grande a fuego medio.",
      "Freír las torrejas por ambos lados hasta que estén doradas y cocidas por dentro.",
      "Retirar y colocar sobre papel absorbente.",
      "Servir calientes, opcionalmente con sirope, miel o azúcar en polvo.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Batido de Mamey (Cubana)",
    ingredients: [
      { name: "mamey maduro", quantity: "1", unit: "unidad grande" },
      { name: "leche", quantity: "2", unit: "tazas" },
      { name: "azúcar", quantity: "al gusto", unit: "unidad" },
      { name: "hielo (opcional)", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Pelar el mamey, quitar el hueso y cortar la pulpa en trozos.",
      "Colocar la pulpa de mamey en una batidora (si hay electricidad) o machacar muy bien con un tenedor en un bol grande.",
      "Añadir la leche y el azúcar al gusto.",
      "Si se usa batidora, licuar hasta que esté suave. Si no, mezclar vigorosamente con un batidor de mano o tenedor hasta que esté lo más homogéneo posible.",
      "Si se desea, añadir hielo y licuar o agitar nuevamente.",
      "Servir frío.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Gallo Pinto con Huevo Frito (Internacional, Alto en Proteínas)",
    ingredients: [
      {
        name: "arroz blanco cocido (del día anterior)",
        quantity: "1",
        unit: "taza",
      },
      { name: "frijoles negros cocidos", quantity: "1", unit: "taza" },
      { name: "cebolla", quantity: "1/4", unit: "unidad picada" },
      { name: "pimiento rojo", quantity: "1/4", unit: "unidad picado" },
      { name: "ajo", quantity: "1", unit: "diente picado" },
      { name: "cilantro fresco", quantity: "1", unit: "cucharada picado" },
      { name: "aceite vegetal", quantity: "1", unit: "cucharada" },
      { name: "salsa Lizano (opcional)", quantity: "1", unit: "cucharada" },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "aceite para freír huevos", quantity: "al gusto", unit: "unidad" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "En una sartén grande, calentar el aceite vegetal a fuego medio.",
      "Sofreír la cebolla, el pimiento y el ajo hasta que estén tiernos.",
      "Añadir el arroz cocido y los frijoles negros cocidos. Mezclar bien.",
      "Incorporar el cilantro picado y la salsa Lizano (si se usa).",
      "Cocinar, revolviendo ocasionalmente, hasta que el arroz y los frijoles estén bien calientes y ligeramente dorados.",
      "Mientras tanto, freír los huevos en otra sartén con un poco de aceite hasta que la clara esté cuajada y la yema al gusto.",
      "Sazonar el gallo pinto con sal y pimienta al gusto.",
      "Servir el gallo pinto caliente y colocar un huevo frito encima de cada porción.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pan con Aguacate y Tomate (Sin Electricidad, Vegetariano)",
    ingredients: [
      { name: "pan integral o rústico", quantity: "2", unit: "rebanadas" },
      { name: "aguacate maduro", quantity: "1/2", unit: "unidad" },
      { name: "tomate", quantity: "1/2", unit: "unidad en rodajas" },
      {
        name: "aceite de oliva virgen extra",
        quantity: "1",
        unit: "cucharadita",
      },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Untar el aguacate machacado o en rodajas sobre las rebanadas de pan.",
      "Colocar las rodajas de tomate encima del aguacate.",
      "Rociar con aceite de oliva.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir inmediatamente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Cereal con Leche y Frutas (Sin Electricidad, Estándar)",
    ingredients: [
      {
        name: "cereal (copos de maíz, avena instantánea)",
        quantity: "1",
        unit: "taza",
      },
      { name: "leche (animal o vegetal)", quantity: "1.5", unit: "tazas" },
      {
        name: "fruta fresca picada (fresas, plátano)",
        quantity: "1/2",
        unit: "taza",
      },
    ],
    instructions: [
      "En un bol, colocar el cereal.",
      "Verter la leche sobre el cereal.",
      "Añadir la fruta fresca picada.",
      "Servir inmediatamente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
];
