import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de desayunos cubanos e internacionales
 */
export const DESAYUNOS: Recipe[] = [
  {
    id: generateId(),
    title: "Tostada de Pan con Aguacate",
    ingredients: [
      { name: "pan integral", quantity: "2", unit: "rebanadas" },
      { name: "aguacate", quantity: "1", unit: "unidad" },
      { name: "sal", quantity: "1", unit: "pizca" },
      { name: "limón", quantity: "1/2", unit: "unidad" },
    ],
    instructions: [
      "Tostar el pan hasta que esté crujiente",
      "Cortar el aguacate por la mitad, quitar el hueso y extraer la pulpa",
      "Machacar el aguacate en un recipiente con un tenedor",
      "Añadir sal y jugo de limón al gusto",
      "Untar el aguacate sobre el pan tostado",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Revoltillo de Huevo con Tomate",
    ingredients: [
      { name: "huevos", quantity: "3", unit: "unidades" },
      { name: "tomate", quantity: "1", unit: "mediano" },
      { name: "cebolla", quantity: "1/2", unit: "pequeña" },
      { name: "aceite", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Picar la cebolla y el tomate en cuadritos pequeños",
      "Batir los huevos en un recipiente y añadir sal al gusto",
      "Calentar el aceite en una sartén a fuego medio",
      "Añadir la cebolla y cocinar hasta que esté transparente",
      "Agregar el tomate y cocinar por 2 minutos más",
      "Verter los huevos batidos y revolver constantemente hasta que estén cocinados pero jugosos",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Avena Remojada con Frutas (Sin Electricidad)",
    ingredients: [
      { name: "avena", quantity: "1/2", unit: "taza" },
      { name: "leche o agua", quantity: "1", unit: "taza" },
      { name: "plátano", quantity: "1", unit: "unidad" },
      { name: "miel", quantity: "1", unit: "cucharada" },
      { name: "canela", quantity: "1/4", unit: "cucharadita" },
    ],
    instructions: [
      "Mezclar la avena con la leche o agua en un recipiente",
      "Añadir miel y canela al gusto",
      "Tapar y dejar reposar durante toda la noche",
      "A la mañana siguiente, cortar el plátano en rodajas",
      "Mezclar con la avena remojada y servir frío",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tostadas Francesas Cubanas",
    ingredients: [
      { name: "pan", quantity: "4", unit: "rebanadas" },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "leche", quantity: "1/4", unit: "taza" },
      { name: "azúcar", quantity: "2", unit: "cucharadas" },
      { name: "canela", quantity: "1/2", unit: "cucharadita" },
      { name: "vainilla", quantity: "1/2", unit: "cucharadita" },
      { name: "mantequilla", quantity: "1", unit: "cucharada" },
    ],
    instructions: [
      "Batir los huevos, leche, azúcar, canela y vainilla en un recipiente hondo",
      "Sumergir cada rebanada de pan en la mezcla, asegurándote que se empape bien",
      "Calentar la mantequilla en una sartén a fuego medio",
      "Cocinar cada rebanada por ambos lados hasta que esté dorada",
      "Servir caliente, opcionalmente con miel o sirope por encima",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Batido de Frutas Tropical (Sin Electricidad)",
    ingredients: [
      { name: "plátano maduro", quantity: "1", unit: "unidad" },
      { name: "mango", quantity: "1", unit: "unidad" },
      { name: "naranja", quantity: "1", unit: "unidad" },
      { name: "agua", quantity: "1/2", unit: "taza" },
      { name: "azúcar", quantity: "1", unit: "cucharada" },
    ],
    instructions: [
      "Pelar y cortar el plátano y el mango en trozos pequeños",
      "Exprimir la naranja y reservar el jugo",
      "En un frasco con tapa, añadir todas las frutas picadas",
      "Agregar el jugo de naranja, agua y azúcar",
      "Cerrar bien el frasco y agitar vigorosamente durante 2-3 minutos",
      "Servir inmediatamente con hielo opcional",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Desayuno Proteico de Frijoles Negros",
    ingredients: [
      { name: "frijoles negros cocidos", quantity: "1", unit: "taza" },
      { name: "huevo", quantity: "1", unit: "unidad" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "ajo", quantity: "1", unit: "diente" },
      { name: "comino", quantity: "1/4", unit: "cucharadita" },
      { name: "aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Picar finamente la cebolla y el ajo",
      "Calentar el aceite en una sartén y sofreír la cebolla y el ajo",
      "Añadir los frijoles negros cocidos y el comino",
      "Machacar ligeramente los frijoles mientras se calientan",
      "Hacer un hueco en el centro y romper el huevo en él",
      "Cocinar hasta que el huevo esté al punto deseado",
      "Servir caliente",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pan con Lechón Desmenuzado",
    ingredients: [
      { name: "pan cubano o baguette", quantity: "1", unit: "unidad" },
      { name: "lechón asado desmenuzado", quantity: "1", unit: "taza" },
      { name: "mojo criollo", quantity: "2", unit: "cucharadas" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "lechuga", quantity: "2", unit: "hojas" },
    ],
    instructions: [
      "Cortar el pan por la mitad a lo largo",
      "Calentar el lechón desmenuzado con un poco de mojo criollo",
      "Picar la cebolla en rodajas finas",
      "Lavar y secar las hojas de lechuga",
      "Montar el sándwich colocando el lechón, la cebolla y la lechuga",
      "Presionar ligeramente y cortar en porciones",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Desayuno",
    dietType: "Alto en proteínas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "d7",
    title: "Tostadas de aguacate y huevo",
    ingredients: [
      { name: "Pan", quantity: "2", unit: "rebanadas" },
      { name: "Aguacate", quantity: "1", unit: "unidad" },
      { name: "Huevos", quantity: "2", unit: "unidades" },
      { name: "Tomate cherry", quantity: "5", unit: "unidades" },
      { name: "Aceite de oliva", quantity: "1", unit: "cucharada" },
      { name: "Sal", quantity: "1", unit: "pizca" },
      { name: "Pimienta", quantity: "1", unit: "pizca" },
      { name: "Zumo de limón", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Tostar el pan hasta que esté dorado y crujiente.",
      "Cortar el aguacate por la mitad, quitar el hueso y machacar la pulpa en un bol.",
      "Añadir el zumo de limón, sal y pimienta al aguacate y mezclar bien.",
      "Extender la mezcla de aguacate sobre las tostadas.",
      "En una sartén con aceite de oliva, freír los huevos al gusto (estrellados o revueltos).",
      "Colocar los huevos sobre las tostadas de aguacate.",
      "Cortar los tomates cherry por la mitad y colocarlos alrededor del plato.",
      "Servir inmediatamente mientras está caliente.",
    ],
    prepTime: "15",
    difficultyLevel: "Fácil",
    cuisineType: "Internacional",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
];
