import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de meriendas cubanas e internacionales
 */
export const MERIENDAS: Recipe[] = [
  // Recetas existentes (manteniendo las originales)
  {
    id: generateId(),
    title: "Plátanos Maduros Fritos",
    ingredients: [
      { name: "plátanos maduros", quantity: "2", unit: "unidades" },
      { name: "aceite", quantity: "1/2", unit: "taza" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Pelar los plátanos maduros y cortarlos en diagonal en rodajas de 1 cm",
      "Calentar el aceite en una sartén a fuego medio-alto",
      "Freír los plátanos hasta que estén dorados por ambos lados",
      "Retirar y colocar sobre papel absorbente para eliminar el exceso de aceite",
      "Añadir una pizca de sal si se desea y servir calientes",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tostones de Plátano Verde",
    ingredients: [
      { name: "plátanos verdes", quantity: "2", unit: "unidades" },
      { name: "aceite", quantity: "1", unit: "taza" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "ajo", quantity: "2", unit: "dientes" },
    ],
    instructions: [
      "Pelar los plátanos verdes y cortarlos en rodajas de 2 cm de grosor",
      "Calentar el aceite en una sartén a fuego medio-alto",
      "Freír las rodajas por 2-3 minutos hasta que estén ligeramente doradas",
      "Retirar y aplastar cada rodaja con un tostonera o plato plano",
      "Volver a freír las rodajas aplastadas hasta que estén crujientes",
      "Escurrir sobre papel absorbente",
      "Machacar el ajo con sal y mezclar con un poco de agua",
      "Rociar los tostones con esta mezcla de ajo antes de servir",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sandwich Cubano",
    ingredients: [
      { name: "pan cubano", quantity: "1", unit: "barra" },
      { name: "jamón", quantity: "100", unit: "gramos" },
      { name: "lechón asado", quantity: "100", unit: "gramos" },
      { name: "queso suizo", quantity: "4", unit: "lonchas" },
      { name: "pepinillos", quantity: "4", unit: "unidades" },
      { name: "mostaza", quantity: "2", unit: "cucharadas" },
      { name: "mantequilla", quantity: "2", unit: "cucharadas" },
    ],
    instructions: [
      "Cortar el pan por la mitad a lo largo",
      "Untar mostaza en ambas mitades del pan",
      "Colocar el jamón, el lechón, el queso y los pepinillos en rodajas",
      "Cerrar el sándwich y untar mantequilla por fuera",
      "Calentar una plancha o sartén a fuego medio",
      "Colocar el sándwich y presionar con una prensa o sartén pesada",
      "Cocinar por ambos lados hasta que el pan esté crujiente y el queso derretido",
      "Cortar en diagonal y servir caliente",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pan con Timba (Sin Electricidad)",
    ingredients: [
      { name: "pan cubano o baguette", quantity: "1", unit: "unidad" },
      { name: "queso crema", quantity: "100", unit: "gramos" },
      { name: "guayaba en pasta", quantity: "100", unit: "gramos" },
    ],
    instructions: [
      "Cortar el pan por la mitad a lo largo",
      "Untar el queso crema en una mitad",
      "Colocar rodajas de pasta de guayaba sobre el queso",
      "Cerrar el sándwich y cortar en porciones",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Frituras de Maíz",
    ingredients: [
      { name: "harina de maíz", quantity: "1", unit: "taza" },
      { name: "agua", quantity: "3/4", unit: "taza" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "aceite", quantity: "2", unit: "tazas" },
    ],
    instructions: [
      "Picar la cebolla muy finamente",
      "Mezclar la harina de maíz, cebolla, sal y agua hasta formar una masa suave",
      "Calentar el aceite en una sartén a fuego medio-alto",
      "Formar pequeñas bolitas con la masa y aplastar ligeramente",
      "Freír hasta que estén doradas y crujientes por ambos lados",
      "Retirar y escurrir sobre papel absorbente",
      "Servir calientes",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Hummus con Palitos de Zanahoria y Pepino (Internacional)",
    ingredients: [
      { name: "garbanzos cocidos", quantity: "400", unit: "gramos" },
      { name: "tahini", quantity: "2", unit: "cucharadas" },
      { name: "jugo de limón", quantity: "2", unit: "cucharadas" },
      { name: "ajo", quantity: "1", unit: "diente" },
      { name: "aceite de oliva", quantity: "2", unit: "cucharadas" },
      { name: "agua fría", quantity: "2-4", unit: "cucharadas" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "zanahorias", quantity: "2", unit: "unidades" },
      { name: "pepino", quantity: "1", unit: "unidad" },
    ],
    instructions: [
      "En un procesador de alimentos, combinar los garbanzos, tahini, jugo de limón, ajo y sal.",
      "Procesar hasta obtener una pasta suave.",
      "Con el procesador en marcha, añadir lentamente el aceite de oliva y el agua fría hasta alcanzar la consistencia deseada.",
      "Pelar y cortar las zanahorias y el pepino en palitos.",
      "Servir el hummus en un bol, rociar con un poco más de aceite de oliva y acompañar con los palitos de vegetales.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Brochetas Caprese (Internacional)",
    ingredients: [
      { name: "tomates cherry", quantity: "200", unit: "gramos" },
      { name: "bolas de mozzarella mini", quantity: "200", unit: "gramos" },
      { name: "hojas de albahaca fresca", quantity: "20", unit: "unidades" },
      {
        name: "aceite de oliva virgen extra",
        quantity: "2",
        unit: "cucharadas",
      },
      { name: "glaseado balsámico", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Lavar los tomates cherry y las hojas de albahaca.",
      "Escurrir las bolas de mozzarella.",
      "Ensamblar las brochetas alternando un tomate cherry, una hoja de albahaca doblada y una bola de mozzarella.",
      "Colocar las brochetas en un plato.",
      "Rociar con aceite de oliva, glaseado balsámico (opcional), sal y pimienta.",
      "Servir inmediatamente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Mariquitas de Plátano Verde (Cubana)",
    ingredients: [
      { name: "plátanos verdes", quantity: "3", unit: "unidades" },
      { name: "aceite para freír", quantity: "suficiente", unit: "unidad" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Pelar los plátanos verdes y cortarlos en rodajas muy finas (idealmente con una mandolina).",
      "Calentar suficiente aceite en una sartén a fuego medio-alto.",
      "Freír las rodajas de plátano en pequeñas tandas hasta que estén doradas y crujientes.",
      "Retirar y colocar sobre papel absorbente para eliminar el exceso de aceite.",
      "Espolvorear con sal inmediatamente.",
      "Servir calientes, solas o con mojo.",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pastelitos de Guayaba y Queso (Cubana)",
    ingredients: [
      { name: "masa de hojaldre", quantity: "1", unit: "paquete" },
      { name: "pasta de guayaba", quantity: "200", unit: "gramos" },
      { name: "queso crema", quantity: "100", unit: "gramos" },
      { name: "huevo batido", quantity: "1", unit: "unidad (para barnizar)" },
    ],
    instructions: [
      "Precalentar el horno a 200°C.",
      "Extender la masa de hojaldre y cortarla en cuadrados o rectángulos.",
      "En un bol, ablandar ligeramente la pasta de guayaba y mezclar con el queso crema.",
      "Colocar una porción del relleno en el centro de la mitad de los cuadrados de hojaldre.",
      "Cubrir con la otra mitad de los cuadrados, sellando los bordes con un tenedor.",
      "Colocar los pastelitos en una bandeja para hornear forrada con papel de horno.",
      "Barnizar la superficie de cada pastelito con huevo batido.",
      "Hornear por 15-20 minutos, o hasta que estén dorados e hinchados.",
      "Dejar enfriar ligeramente antes de servir.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Edamame al Vapor con Sal Marina (Internacional, Bajo en Calorías)",
    ingredients: [
      { name: "edamame (vainas)", quantity: "500", unit: "gramos (congelado)" },
      { name: "sal marina gruesa", quantity: "al gusto", unit: "unidad" },
      { name: "agua", quantity: "para cocinar al vapor", unit: "unidad" },
    ],
    instructions: [
      "Llenar una olla con unos centímetros de agua y colocar una cesta para cocinar al vapor dentro.",
      "Llevar el agua a ebullición.",
      "Colocar las vainas de edamame en la cesta de vapor.",
      "Tapar la olla y cocinar al vapor por 5-7 minutos, o hasta que estén tiernas.",
      "Retirar del fuego y transferir el edamame a un bol.",
      "Espolvorear generosamente con sal marina gruesa.",
      "Servir caliente.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Guacamole con Totopos (Internacional, Vegetariano)",
    ingredients: [
      { name: "aguacates maduros", quantity: "2", unit: "unidades" },
      {
        name: "cebolla roja",
        quantity: "1/4",
        unit: "unidad pequeña picada finamente",
      },
      { name: "tomate", quantity: "1", unit: "unidad pequeña picado" },
      { name: "cilantro fresco", quantity: "2", unit: "cucharadas picado" },
      { name: "jugo de limón", quantity: "1", unit: "cucharada" },
      { name: "sal", quantity: "al gusto", unit: "unidad" },
      { name: "pimienta", quantity: "al gusto", unit: "unidad" },
      { name: "totopos de maíz", quantity: "para acompañar", unit: "unidad" },
    ],
    instructions: [
      "Cortar los aguacates por la mitad, quitar el hueso y extraer la pulpa a un bol.",
      "Machacar el aguacate con un tenedor hasta obtener la consistencia deseada (más o menos troceado).",
      "Añadir la cebolla roja picada, el tomate picado y el cilantro picado.",
      "Incorporar el jugo de limón, sal y pimienta al gusto.",
      "Mezclar suavemente para combinar todos los ingredientes.",
      "Probar y ajustar la sazón si es necesario.",
      "Servir inmediatamente con totopos de maíz.",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Vegetariano",
    createdAt: new Date().toISOString(),
  },
];
