import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de meriendas cubanas e internacionales
 */
export const MERIENDAS: Recipe[] = [
  {
    id: generateId(),
    title: "Plátanos Maduros Fritos",
    ingredients: [
      { name: "plátanos maduros", quantity: "2", unit: "unidades" },
      { name: "aceite", quantity: "1/2", unit: "taza" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Pelar los plátanos maduros y cortarlos en diagonal en rodajas de 1 cm",
      "Calentar el aceite en una sartén a fuego medio-alto",
      "Freír los plátanos hasta que estén dorados por ambos lados",
      "Retirar y colocar sobre papel absorbente para eliminar el exceso de aceite",
      "Añadir una pizca de sal si se desea y servir calientes",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tostones de Plátano Verde",
    ingredients: [
      { name: "plátanos verdes", quantity: "2", unit: "unidades" },
      { name: "aceite", quantity: "1", unit: "taza" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "ajo", quantity: "2", unit: "dientes" },
    ],
    instructions: [
      "Pelar los plátanos verdes y cortarlos en rodajas de 2 cm de grosor",
      "Calentar el aceite en una sartén a fuego medio-alto",
      "Freír las rodajas por 2-3 minutos hasta que estén ligeramente doradas",
      "Retirar y aplastar cada rodaja con un tostonera o plato plano",
      "Volver a freír las rodajas aplastadas hasta que estén crujientes",
      "Escurrir sobre papel absorbente",
      "Machacar el ajo con sal y mezclar con un poco de agua",
      "Rociar los tostones con esta mezcla de ajo antes de servir",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Sandwich Cubano",
    ingredients: [
      { name: "pan cubano", quantity: "1", unit: "barra" },
      { name: "jamón", quantity: "100", unit: "gramos" },
      { name: "lechón asado", quantity: "100", unit: "gramos" },
      { name: "queso suizo", quantity: "4", unit: "lonchas" },
      { name: "pepinillos", quantity: "4", unit: "unidades" },
      { name: "mostaza", quantity: "2", unit: "cucharadas" },
      { name: "mantequilla", quantity: "2", unit: "cucharadas" },
    ],
    instructions: [
      "Cortar el pan por la mitad a lo largo",
      "Untar mostaza en ambas mitades del pan",
      "Colocar el jamón, el lechón, el queso y los pepinillos en rodajas",
      "Cerrar el sándwich y untar mantequilla por fuera",
      "Calentar una plancha o sartén a fuego medio",
      "Colocar el sándwich y presionar con una prensa o sartén pesada",
      "Cocinar por ambos lados hasta que el pan esté crujiente y el queso derretido",
      "Cortar en diagonal y servir caliente",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Pan con Timba (Sin Electricidad)",
    ingredients: [
      { name: "pan cubano o baguette", quantity: "1", unit: "unidad" },
      { name: "queso crema", quantity: "100", unit: "gramos" },
      { name: "guayaba en pasta", quantity: "100", unit: "gramos" },
    ],
    instructions: [
      "Cortar el pan por la mitad a lo largo",
      "Untar el queso crema en una mitad",
      "Colocar rodajas de pasta de guayaba sobre el queso",
      "Cerrar el sándwich y cortar en porciones",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Frituras de Maíz",
    ingredients: [
      { name: "harina de maíz", quantity: "1", unit: "taza" },
      { name: "agua", quantity: "3/4", unit: "taza" },
      { name: "cebolla", quantity: "1/4", unit: "unidad" },
      { name: "sal", quantity: "1", unit: "cucharadita" },
      { name: "aceite", quantity: "2", unit: "tazas" },
    ],
    instructions: [
      "Picar la cebolla muy finamente",
      "Mezclar la harina de maíz, cebolla, sal y agua hasta formar una masa suave",
      "Calentar el aceite en una sartén a fuego medio-alto",
      "Formar pequeñas bolitas con la masa y aplastar ligeramente",
      "Freír hasta que estén doradas y crujientes por ambos lados",
      "Retirar y escurrir sobre papel absorbente",
      "Servir calientes",
    ],
    prepTime: "15-30 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Merienda",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
];
