import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de postres cubanos e internacionales
 */
export const POSTRES: Recipe[] = [
  {
    id: generateId(),
    title: "Arroz con Leche Tradicional",
    ingredients: [
      { name: "arroz", quantity: "1", unit: "taza" },
      { name: "leche", quantity: "4", unit: "tazas" },
      { name: "azúcar", quantity: "3/4", unit: "taza" },
      { name: "canela en rama", quantity: "2", unit: "unidades" },
      { name: "cáscara de limón", quantity: "1", unit: "unidad" },
      { name: "canela en polvo", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Lavar el arroz con agua fría",
      "En una olla, hervir 2 tazas de agua con la canela en rama y la cáscara de limón",
      "Añadir el arroz y cocinar a fuego medio hasta que absorba el agua",
      "Agregar la leche gradualmente, removiendo constantemente",
      "Añadir el azúcar y seguir cocinando a fuego lento hasta que el arroz esté tierno y la mezcla espese",
      "Retirar la canela y la cáscara de limón",
      "Servir en recipientes individuales y espolvorear con canela en polvo",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Frutas (Sin Electricidad)",
    ingredients: [
      { name: "manzana", quantity: "1", unit: "unidad" },
      { name: "plátano", quantity: "1", unit: "unidad" },
      { name: "naranja", quantity: "1", unit: "unidad" },
      { name: "piña", quantity: "1/4", unit: "unidad" },
      { name: "miel", quantity: "1", unit: "cucharada" },
      { name: "limón", quantity: "1/2", unit: "unidad" },
    ],
    instructions: [
      "Pelar y cortar todas las frutas en trozos pequeños",
      "Colocar en un recipiente grande",
      "Rociar con el jugo de limón para evitar que se oscurezcan",
      "Añadir la miel y mezclar suavemente",
      "Refrigerar por al menos 30 minutos antes de servir o servir inmediatamente si no hay refrigerador",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Postre",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Flan de Leche Cubano",
    ingredients: [
      { name: "huevos", quantity: "5", unit: "unidades" },
      { name: "leche condensada", quantity: "1", unit: "lata" },
      { name: "leche evaporada", quantity: "1", unit: "lata" },
      { name: "vainilla", quantity: "1", unit: "cucharadita" },
      { name: "azúcar", quantity: "1/2", unit: "taza" },
    ],
    instructions: [
      "Precalentar el horno a 180°C",
      "Para el caramelo: derretir el azúcar en una sartén a fuego medio hasta obtener un color dorado",
      "Verter el caramelo en un molde para flan, asegurándote de cubrir el fondo",
      "En un recipiente aparte, batir los huevos",
      "Añadir la leche condensada, leche evaporada y vainilla, mezclar bien",
      "Verter la mezcla en el molde sobre el caramelo",
      "Colocar el molde en un baño maría en el horno",
      "Hornear por 45-50 minutos o hasta que al insertar un cuchillo salga limpio",
      "Dejar enfriar y refrigerar por al menos 2 horas",
      "Desmoldar cuidadosamente y servir",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Boniatillo (Dulce de Boniato)",
    ingredients: [
      { name: "boniato (batata)", quantity: "1", unit: "kg" },
      { name: "azúcar", quantity: "2", unit: "tazas" },
      { name: "agua", quantity: "1", unit: "taza" },
      { name: "canela", quantity: "1", unit: "cucharadita" },
      { name: "vainilla", quantity: "1", unit: "cucharadita" },
      { name: "limón", quantity: "1/2", unit: "unidad" },
    ],
    instructions: [
      "Pelar y cortar el boniato en trozos",
      "Hervirlo en agua hasta que esté muy blando",
      "Escurrir y hacer un puré con un tenedor o machacador",
      "En una olla, preparar un almíbar con el azúcar y el agua",
      "Cuando el almíbar esté a punto de hebra fina, añadir el puré de boniato",
      "Añadir la canela, la vainilla y ralladuras de la cáscara de limón",
      "Cocinar a fuego lento, removiendo constantemente para evitar que se pegue",
      "Cuando la mezcla espese y se despegue del fondo de la olla, está lista",
      "Servir en pequeños recipientes y dejar enfriar",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Dulce de Coco (Sin Electricidad)",
    ingredients: [
      { name: "coco rallado", quantity: "2", unit: "tazas" },
      { name: "azúcar", quantity: "1", unit: "taza" },
      { name: "agua", quantity: "1/2", unit: "taza" },
      { name: "canela", quantity: "1/2", unit: "cucharadita" },
      { name: "vainilla", quantity: "1/2", unit: "cucharadita" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Mezclar el agua y el azúcar en una olla",
      "Llevar a ebullición hasta formar un almíbar",
      "Añadir el coco rallado, la canela, la vainilla y la pizca de sal",
      "Cocinar a fuego lento, removiendo constantemente",
      "Cuando la mezcla espese y el coco esté translúcido, retirar del fuego",
      "Dejar enfriar ligeramente y formar pequeñas bolitas",
      "Colocar en papel encerado y dejar enfriar completamente",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
];
