import type { Recipe } from "../../types/recipe";
import { generateId } from "../../services/storage/storageService";

/**
 * Recetas de postres cubanos e internacionales
 */
export const POSTRES: Recipe[] = [
  // Recetas existentes (manteniendo las originales)
  {
    id: generateId(),
    title: "Arroz con Leche Tradicional",
    ingredients: [
      { name: "arroz", quantity: "1", unit: "taza" },
      { name: "leche", quantity: "4", unit: "tazas" },
      { name: "azúcar", quantity: "3/4", unit: "taza" },
      { name: "canela en rama", quantity: "2", unit: "unidades" },
      { name: "cáscara de limón", quantity: "1", unit: "unidad" },
      { name: "canela en polvo", quantity: "1", unit: "cucharadita" },
    ],
    instructions: [
      "Lavar el arroz con agua fría",
      "En una olla, hervir 2 tazas de agua con la canela en rama y la cáscara de limón",
      "Añadir el arroz y cocinar a fuego medio hasta que absorba el agua",
      "Agregar la leche gradualmente, removiendo constantemente",
      "Añadir el azúcar y seguir cocinando a fuego lento hasta que el arroz esté tierno y la mezcla espese",
      "Retirar la canela y la cáscara de limón",
      "Servir en recipientes individuales y espolvorear con canela en polvo",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Ensalada de Frutas (Sin Electricidad)",
    ingredients: [
      { name: "manzana", quantity: "1", unit: "unidad" },
      { name: "plátano", quantity: "1", unit: "unidad" },
      { name: "naranja", quantity: "1", unit: "unidad" },
      { name: "piña", quantity: "1/4", unit: "unidad" },
      { name: "miel", quantity: "1", unit: "cucharada" },
      { name: "limón", quantity: "1/2", unit: "unidad" },
    ],
    instructions: [
      "Pelar y cortar todas las frutas en trozos pequeños",
      "Colocar en un recipiente grande",
      "Rociar con el jugo de limón para evitar que se oscurezcan",
      "Añadir la miel y mezclar suavemente",
      "Refrigerar por al menos 30 minutos antes de servir o servir inmediatamente si no hay refrigerador",
    ],
    prepTime: "< 15 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Postre",
    dietType: "Bajo en calorías",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Flan de Leche Cubano",
    ingredients: [
      { name: "huevos", quantity: "5", unit: "unidades" },
      { name: "leche condensada", quantity: "1", unit: "lata" },
      { name: "leche evaporada", quantity: "1", unit: "lata" },
      { name: "vainilla", quantity: "1", unit: "cucharadita" },
      { name: "azúcar", quantity: "1/2", unit: "taza" },
    ],
    instructions: [
      "Precalentar el horno a 180°C",
      "Para el caramelo: derretir el azúcar en una sartén a fuego medio hasta obtener un color dorado",
      "Verter el caramelo en un molde para flan, asegurándote de cubrir el fondo",
      "En un recipiente aparte, batir los huevos",
      "Añadir la leche condensada, leche evaporada y vainilla, mezclar bien",
      "Verter la mezcla en el molde sobre el caramelo",
      "Colocar el molde en un baño maría en el horno",
      "Hornear por 45-50 minutos o hasta que al insertar un cuchillo salga limpio",
      "Dejar enfriar y refrigerar por al menos 2 horas",
      "Desmoldar cuidadosamente y servir",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Boniatillo (Dulce de Boniato)",
    ingredients: [
      { name: "boniato (batata)", quantity: "1", unit: "kg" },
      { name: "azúcar", quantity: "2", unit: "tazas" },
      { name: "agua", quantity: "1", unit: "taza" },
      { name: "canela", quantity: "1", unit: "cucharadita" },
      { name: "vainilla", quantity: "1", unit: "cucharadita" },
      { name: "limón", quantity: "1/2", unit: "unidad" },
    ],
    instructions: [
      "Pelar y cortar el boniato en trozos",
      "Hervirlo en agua hasta que esté muy blando",
      "Escurrir y hacer un puré con un tenedor o machacador",
      "En una olla, preparar un almíbar con el azúcar y el agua",
      "Cuando el almíbar esté a punto de hebra fina, añadir el puré de boniato",
      "Añadir la canela, la vainilla y ralladuras de la cáscara de limón",
      "Cocinar a fuego lento, removiendo constantemente para evitar que se pegue",
      "Cuando la mezcla espese y se despegue del fondo de la olla, está lista",
      "Servir en pequeños recipientes y dejar enfriar",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Dulce de Coco (Sin Electricidad)",
    ingredients: [
      { name: "coco rallado", quantity: "2", unit: "tazas" },
      { name: "azúcar", quantity: "1", unit: "taza" },
      { name: "agua", quantity: "1/2", unit: "taza" },
      { name: "canela", quantity: "1/2", unit: "cucharadita" },
      { name: "vainilla", quantity: "1/2", unit: "cucharadita" },
      { name: "sal", quantity: "1", unit: "pizca" },
    ],
    instructions: [
      "Mezclar el agua y el azúcar en una olla",
      "Llevar a ebullición hasta formar un almíbar",
      "Añadir el coco rallado, la canela, la vainilla y la pizca de sal",
      "Cocinar a fuego lento, removiendo constantemente",
      "Cuando la mezcla espese y el coco esté translúcido, retirar del fuego",
      "Dejar enfriar ligeramente y formar pequeñas bolitas",
      "Colocar en papel encerado y dejar enfriar completamente",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Brownies de Chocolate (Internacional)",
    ingredients: [
      { name: "mantequilla sin sal", quantity: "1/2", unit: "taza derretida" },
      { name: "azúcar", quantity: "1", unit: "taza" },
      { name: "huevos", quantity: "2", unit: "unidades" },
      { name: "extracto de vainilla", quantity: "1", unit: "cucharadita" },
      { name: "cacao en polvo sin azúcar", quantity: "1/3", unit: "taza" },
      { name: "harina de trigo", quantity: "1/2", unit: "taza" },
      { name: "sal", quantity: "1/4", unit: "cucharadita" },
      { name: "chispas de chocolate", quantity: "1/2", unit: "taza" },
    ],
    instructions: [
      "Precalentar el horno a 175°C. Engrasar y enharinar un molde cuadrado de 20 cm.",
      "En un bol grande, mezclar la mantequilla derretida y el azúcar.",
      "Incorporar los huevos uno a uno, batiendo bien después de cada adición.",
      "Añadir el extracto de vainilla.",
      "En un bol aparte, cernir el cacao en polvo, la harina y la sal.",
      "Añadir los ingredientes secos a los húmedos y mezclar hasta que estén combinados.",
      "Incorporar las chispas de chocolate.",
      "Verter la masa en el molde preparado y extender uniformemente.",
      "Hornear por 20-25 minutos, o hasta que al insertar un palillo en el centro, éste salga con algunas migas húmedas (no completamente limpio).",
      "Dejar enfriar completamente en el molde antes de cortar en cuadrados.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Tiramisú (Internacional)",
    ingredients: [
      { name: "bizcochos de soletilla", quantity: "24", unit: "unidades" },
      { name: "café espresso frío", quantity: "1.5", unit: "tazas" },
      { name: "licor de café (opcional)", quantity: "2", unit: "cucharadas" },
      { name: "yemas de huevo", quantity: "4", unit: "unidades" },
      { name: "azúcar", quantity: "1/2", unit: "taza" },
      { name: "queso mascarpone", quantity: "500", unit: "gramos" },
      {
        name: "nata para montar (crema de leche)",
        quantity: "1",
        unit: "taza fría",
      },
      {
        name: "cacao en polvo sin azúcar",
        quantity: "para espolvorear",
        unit: "unidad",
      },
    ],
    instructions: [
      "En un bol pequeño, mezclar el café espresso frío y el licor de café (si se usa).",
      "En un bol resistente al calor, batir las yemas de huevo y el azúcar hasta que estén pálidas y espesas.",
      "Colocar el bol sobre una olla con agua hirviendo a fuego lento (baño maría), asegurándose de que el fondo del bol no toque el agua.",
      "Batir constantemente por unos 5-7 minutos, hasta que la mezcla esté caliente y haya espesado.",
      "Retirar del baño maría y seguir batiendo hasta que se enfríe.",
      "En otro bol, batir el queso mascarpone hasta que esté suave.",
      "En un bol aparte, montar la nata fría hasta que forme picos suaves.",
      "Incorporar suavemente la mezcla de yemas al mascarpone.",
      "Luego, incorporar la nata montada con movimientos envolventes.",
      "Mojar rápidamente cada bizcocho de soletilla en la mezcla de café y colocar una capa en el fondo de un recipiente para servir.",
      "Cubrir con una capa de la crema de mascarpone.",
      "Repetir las capas hasta terminar con crema de mascarpone.",
      "Cubrir y refrigerar por al menos 4 horas, o preferiblemente toda la noche.",
      "Antes de servir, espolvorear generosamente con cacao en polvo.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  // --- Más recetas de Postre generadas ---
  {
    id: generateId(),
    title: "Cascos de Guayaba con Queso Crema (Cubana, Sin Electricidad)",
    ingredients: [
      { name: "guayabas maduras", quantity: "6", unit: "unidades" },
      { name: "azúcar", quantity: "1", unit: "taza" },
      { name: "agua", quantity: "1/2", unit: "taza" },
      { name: "queso crema", quantity: "200", unit: "gramos" },
    ],
    instructions: [
      "Lavar las guayabas, cortar los extremos y partirlas por la mitad.",
      "Con una cuchara, retirar las semillas del centro de cada mitad.",
      "En una olla, combinar las mitades de guayaba (los 'cascos'), el azúcar y el agua.",
      "Cocinar a fuego medio-bajo, revolviendo ocasionalmente, hasta que las guayabas estén tiernas y el almíbar espese (aproximadamente 20-30 minutos).",
      "Dejar enfriar completamente.",
      "Servir los cascos de guayaba con una porción de queso crema al lado.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Fácil",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Natilla Cubana",
    ingredients: [
      { name: "leche entera", quantity: "4", unit: "tazas" },
      { name: "azúcar", quantity: "1", unit: "taza" },
      { name: "yemas de huevo", quantity: "6", unit: "unidades" },
      { name: "maicena (fécula de maíz)", quantity: "3", unit: "cucharadas" },
      { name: "cáscara de limón", quantity: "1", unit: "tira" },
      { name: "canela en rama", quantity: "1", unit: "unidad" },
      { name: "canela en polvo", quantity: "para decorar", unit: "unidad" },
    ],
    instructions: [
      "En una olla, calentar la leche con la cáscara de limón y la canela en rama a fuego medio, sin que llegue a hervir.",
      "En un bol aparte, batir las yemas de huevo con el azúcar hasta que estén pálidas.",
      "Disolver la maicena en un poco de leche fría y añadir a las yemas batidas. Mezclar bien.",
      "Retirar la cáscara de limón y la canela de la leche caliente.",
      "Verter gradualmente la leche caliente sobre la mezcla de yemas, batiendo constantemente.",
      "Regresar la mezcla a la olla y cocinar a fuego medio-bajo, revolviendo constantemente con una cuchara de madera, hasta que espese (aproximadamente 10-15 minutos). No dejar que hierva.",
      "Retirar del fuego y verter en recipientes individuales.",
      "Dejar enfriar y refrigerar por al menos 2 horas.",
      "Antes de servir, espolvorear con canela en polvo.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Mousse de Chocolate (Internacional, Intermedia)",
    ingredients: [
      {
        name: "chocolate negro (70% cacao)",
        quantity: "200",
        unit: "gramos picado",
      },
      { name: "mantequilla sin sal", quantity: "50", unit: "gramos" },
      {
        name: "huevos",
        quantity: "4",
        unit: "unidades (separadas yemas y claras)",
      },
      { name: "azúcar", quantity: "50", unit: "gramos" },
      {
        name: "nata para montar (crema de leche)",
        quantity: "200",
        unit: "ml fría",
      },
      { name: "extracto de vainilla", quantity: "1", unit: "cucharadita" },
      { name: "una pizca de sal", quantity: "al gusto", unit: "unidad" },
    ],
    instructions: [
      "Derretir el chocolate picado y la mantequilla al baño maría o en el microondas en intervalos cortos, revolviendo hasta obtener una mezcla suave.",
      "Dejar enfriar ligeramente.",
      "En un bol, batir las yemas de huevo con la mitad del azúcar hasta que estén pálidas y cremosas.",
      "Añadir el extracto de vainilla y mezclar.",
      "Incorporar la mezcla de chocolate derretido a las yemas batidas, mezclando bien.",
      "En otro bol limpio, batir las claras de huevo con la pizca de sal hasta que formen picos suaves.",
      "Añadir el azúcar restante gradualmente mientras se sigue batiendo hasta obtener picos firmes.",
      "En un tercer bol, montar la nata fría hasta que forme picos suaves.",
      "Incorporar suavemente un tercio de las claras montadas a la mezcla de chocolate para aligerarla.",
      "Luego, incorporar el resto de las claras montadas con movimientos envolventes, con cuidado de no bajar el aire.",
      "Finalmente, incorporar la nata montada con movimientos envolventes hasta que esté todo bien combinado y aireado.",
      "Verter la mousse en copas individuales o un recipiente grande.",
      "Refrigerar por al menos 4 horas, o preferiblemente toda la noche, hasta que esté firme.",
      "Decorar antes de servir con cacao en polvo, virutas de chocolate o nata montada adicional.",
    ],
    prepTime: "30-60 minutos",
    difficultyLevel: "Intermedia",
    cuisineType: "Postre",
    dietType: "Estándar",
    createdAt: new Date().toISOString(),
  },
];
